<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Regular_fa fa-edit_1</name>
   <tag></tag>
   <elementGuidId>818643e3-ba6c-44bc-8c85-07e400fc8bc6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='DemandRequestTable']/tbody/tr[2]/td[5]/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>b2345d66-151e-4f2e-898f-90238a8a3419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-edit</value>
      <webElementGuid>59bc50fc-1714-4c20-802a-99601fc3d8af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DemandRequestTable&quot;)/tbody[1]/tr[@class=&quot;even&quot;]/td[@class=&quot;text-center&quot;]/a[@class=&quot;Action Update&quot;]/i[@class=&quot;fa fa-edit&quot;]</value>
      <webElementGuid>5fe20059-0a53-4179-a15e-cae0c0b64779</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='DemandRequestTable']/tbody/tr[2]/td[5]/a/i</value>
      <webElementGuid>05fc2585-4f41-4585-a99e-c5ec59a42936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[5]/a/i</value>
      <webElementGuid>53985d54-5127-4acc-85db-2b8bcc72b0a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
