<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Mr. Muhammad Mudassar_PrintInModal</name>
   <tag></tag>
   <elementGuidId>fcc6ae54-5bcb-41ca-bd2c-d593c84331fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PrintInModal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='PrintInModal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8c9d2be7-1216-41c6-b2c4-408ecf35048d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PrintInModal</value>
      <webElementGuid>c5176d7c-7baa-4a1e-a1ad-7e1c0cfdcaca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Print</value>
      <webElementGuid>e3ebc675-1082-4248-a162-a0c5cbb02abc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>PrintInModal service-grid barcode btn btn-sm btn-clean btn-icon btn-icon-md</value>
      <webElementGuid>619cb03c-ac98-4051-be01-c56d35a62d00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PrintInModal&quot;)</value>
      <webElementGuid>16d13c67-ba6b-4ac2-8156-979c257bfec4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='PrintInModal']</value>
      <webElementGuid>f72ee12f-4797-4863-9626-a0c0eed6169d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='VerifiedQueueTable']/tbody/tr/td[10]/a[8]</value>
      <webElementGuid>7f7d38dd-ac2a-4e7f-ab1f-c46fd39660bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mr. Muhammad Mudassar'])[3]/following::a[8]</value>
      <webElementGuid>a0f4934f-7e17-4667-ac7b-d6e4dd98045d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CK-MB'])[1]/following::a[8]</value>
      <webElementGuid>fabc9ce8-136f-47cf-81a5-6a9c18cc8197</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Processing...'])[4]/preceding::a[13]</value>
      <webElementGuid>46445c0f-3af2-4185-be89-17073f26c185</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 1 to 1 of 1 entries'])[1]/preceding::a[13]</value>
      <webElementGuid>309dd032-01d2-48a0-97bd-043953a80f8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[8]</value>
      <webElementGuid>760c28cf-24f5-4865-8043-0091b1306098</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'PrintInModal' and @title = 'Print']</value>
      <webElementGuid>4dac0806-96d9-40b6-af27-b377993a612a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
