<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Please enter a value with valid lengt_bf4d4b</name>
   <tag></tag>
   <elementGuidId>931982a7-e232-49df-90e7-ee86cfabb843</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SubmitPatient</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='SubmitPatient']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>da01feaf-cda8-4722-8e4f-d11b26a3f79e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SubmitPatient</value>
      <webElementGuid>af43ff97-a3e2-49b5-8f2e-2a89147962ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>768d47c4-a604-4d79-8e57-3b7392662c65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Check In</value>
      <webElementGuid>330039be-89b7-468b-8ade-f00042dff665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary pull-right</value>
      <webElementGuid>ead55cb9-41cc-40a5-8bf1-11f99e805cd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SubmitPatient&quot;)</value>
      <webElementGuid>b744f58e-1c26-4418-8d72-027250d47997</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='SubmitPatient']</value>
      <webElementGuid>b90f20f8-2c50-4af0-9507-ca468a639e99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CheckedInDiv_Wrapper']/div[5]/div[2]/input</value>
      <webElementGuid>59878574-3f7c-4c61-b93b-a5f6fd98bf52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/input</value>
      <webElementGuid>fc47a9c0-737c-43e8-8679-1e8eb21352ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'SubmitPatient' and @type = 'button']</value>
      <webElementGuid>bec054ca-6e47-4fa8-af47-8ffc87f82f96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
