<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Address</name>
   <tag></tag>
   <elementGuidId>33deeb72-ffff-4a6b-a2d7-5513496c8e96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AddressNew</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AddressNew']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>73cbf5ba-64d7-4d2f-bc08-f57977aa49af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AddressNew</value>
      <webElementGuid>f07fdf8a-b15e-44f0-8823-71830bcd692d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>666d5ea7-589c-4915-aca7-5755cd64e5e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Address</value>
      <webElementGuid>1427f85f-139c-44c9-82ae-a456f394f2ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ebcfb6fe-ce2e-4e57-a09b-a017e5767d17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Address</value>
      <webElementGuid>667d838a-9cd7-4796-9345-f099bfc7853a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bv-field</name>
      <type>Main</type>
      <value>Address</value>
      <webElementGuid>a05960c1-cee0-483d-9fe9-4b2938e88586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AddressNew&quot;)</value>
      <webElementGuid>ff05476d-be4c-42e5-821a-5a6576e0fc8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AddressNew']</value>
      <webElementGuid>d8bf2834-bb8d-4c1c-ad0a-5ff37dcb2d1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='UserEducationDatatableDiv']/div[2]/div/div[6]/div[2]/div[2]/input)[2]</value>
      <webElementGuid>a9e8c2ea-ec3e-4b16-aeb5-488306c83dc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[6]/div[2]/div[2]/input</value>
      <webElementGuid>a80aee50-d489-455e-8069-8c0de01c2198</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'AddressNew' and @type = 'text' and @name = 'Address' and @placeholder = 'Address']</value>
      <webElementGuid>72666201-89e2-415b-abe4-e4d94e0ade6a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
