<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_asd_Action Delete btn btn-sm btn-clean bt_597cbe</name>
   <tag></tag>
   <elementGuidId>c0c8d4db-eceb-4230-a859-27f79ce3f7b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.Action.Delete.btn.btn-sm.btn-clean.btn-icon.btn-icon-md</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='PanalOrganizationTeble']/tbody/tr/td[4]/a[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c2178036-36d1-4841-bfcc-9d6efe4b5122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>bb2db7c8-5c2c-4368-9832-2da2d1fbd81a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Action Delete btn btn-sm btn-clean btn-icon btn-icon-md</value>
      <webElementGuid>e4635b5b-4b3c-4433-a9c7-a93334571222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PanalOrganizationTeble&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;text-center&quot;]/a[@class=&quot;Action Delete btn btn-sm btn-clean btn-icon btn-icon-md&quot;]</value>
      <webElementGuid>5c2715a1-2e17-443a-b7a8-937d391f98bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='PanalOrganizationTeble']/tbody/tr/td[4]/a[3]</value>
      <webElementGuid>8a4f21c1-6a66-424c-a2f3-456005014021</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='asd'])[1]/following::a[3]</value>
      <webElementGuid>00f6a6b0-89ee-485d-a052-74e320e9d1c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asd'])[1]/following::a[3]</value>
      <webElementGuid>f8c6a862-4bb8-4891-bd83-b0269a174c82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hassan'])[1]/preceding::a[2]</value>
      <webElementGuid>30fc0061-1375-4f46-8338-864bc246eb7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sehat Card'])[1]/preceding::a[6]</value>
      <webElementGuid>2685cfef-148e-4a6a-902d-f0f6373b8700</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/a[3]</value>
      <webElementGuid>e31506ff-dd77-4366-b33e-5230002995b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Delete']</value>
      <webElementGuid>0a42b28c-4bb2-48f7-9ff3-b72779f38c92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
