<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select Discount Type                _9b6e76</name>
   <tag></tag>
   <elementGuidId>6e5562a6-ff5e-4bee-be6c-5ebceda19dd9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PanelPakageDiscounType</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='PanelPakageDiscounType']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4ac681f9-cc6e-4410-addb-6ad4b55fdc46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PanelPakageDiscounType</value>
      <webElementGuid>a43afd94-8cce-4b01-9b2c-e877b2bd1bd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PanelPackageDiscountType</value>
      <webElementGuid>3c3b16bf-acec-4fad-8374-11043a83f514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectpicker form-control</value>
      <webElementGuid>de442d7f-fb6b-4383-ac3a-b31c849503a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>517e5843-bf48-47e5-8a19-fc8242681917</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>39206910-c0a0-4429-9c48-17920c50f22e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-98</value>
      <webElementGuid>db934208-6774-4367-a994-302ef846e701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                    Select Discount Type
                                                    Gold
                                                    Silver
                                                    Bronze
                                                </value>
      <webElementGuid>1385c1d9-69e7-46b6-9acf-709f08b13507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PanelPakageDiscounType&quot;)</value>
      <webElementGuid>c3afc71a-ed60-4fc2-adfd-f3f700ba246d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='PanelPakageDiscounType']</value>
      <webElementGuid>196c9026-20e9-4095-a9cd-ca1b4ad5d62e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='PanalPackageForm']/div/div/div[4]/div[2]/div/select</value>
      <webElementGuid>bf4fa2a1-96d3-4923-a6bf-f0902416d6d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Package Discount Type'])[1]/following::select[1]</value>
      <webElementGuid>1720c485-5688-4eba-80af-be2f20a45eb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please enter less than 500 characters'])[3]/following::select[1]</value>
      <webElementGuid>857c9de6-d176-4b1b-8309-3858b8dcb666</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Discount Type'])[2]/preceding::select[1]</value>
      <webElementGuid>06b2d6c3-ea87-48fa-adb0-08284f8754ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Discount Type'])[3]/preceding::select[1]</value>
      <webElementGuid>cb3e8fcd-4100-49e6-a4b5-0d561c348755</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>32601d92-ef85-4c64-b192-2ff8d872da55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'PanelPakageDiscounType' and @name = 'PanelPackageDiscountType' and (text() = '
                                                    Select Discount Type
                                                    Gold
                                                    Silver
                                                    Bronze
                                                ' or . = '
                                                    Select Discount Type
                                                    Gold
                                                    Silver
                                                    Bronze
                                                ')]</value>
      <webElementGuid>9501632f-c350-4edb-b7c3-626b04ad1e20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
