<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Acute Limbs Ischemia Intervention</name>
   <tag></tag>
   <elementGuidId>69353b7d-d16e-4130-80e8-7f4d0b6e4287</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='bs-select-1-1']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bs-select-1-1 > span.text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>df30727d-a0c2-4a90-87e6-7b584debf59a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1f8b6cb8-0e65-49d8-a03f-65cd0aed45fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Acute Limbs Ischemia Intervention</value>
      <webElementGuid>3159304d-cf50-4be6-bc93-e99e60b12320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bs-select-1-1&quot;)/span[@class=&quot;text&quot;]</value>
      <webElementGuid>26b792ea-fad7-4cf8-acbd-7b46f10a7b82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='bs-select-1-1']/span</value>
      <webElementGuid>4d8e6540-16b2-428f-9327-0237c223cb98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Procedure'])[3]/following::span[1]</value>
      <webElementGuid>d260cc01-37a8-4865-a9ef-93de32975058</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Procedure'])[2]/following::span[2]</value>
      <webElementGuid>93fa7c2d-4b01-448c-910c-95127c5bd54d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Acute Stroke Intervention'])[2]/preceding::span[1]</value>
      <webElementGuid>304a5049-6e55-4c3c-bf7b-ff04b634e667</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anesthesia Cover'])[2]/preceding::span[2]</value>
      <webElementGuid>30a12caf-a45a-43fa-aa89-92a08fd0ddc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[2]/a/span</value>
      <webElementGuid>642d763f-42a2-4a21-b0d6-4a8509393de6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Acute Limbs Ischemia Intervention' or . = 'Acute Limbs Ischemia Intervention')]</value>
      <webElementGuid>7f1bb5b2-ff86-4884-b12e-84cdb7a55bf9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
