<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Name</name>
   <tag></tag>
   <elementGuidId>93c818a1-96a0-471c-b3d9-4ac9ddec2b8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f42ef529-74bd-4cfe-bb26-d8a2886a3464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>633e4cf5-cb2c-474a-b697-76920ad4d211</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>e5f4d46a-70b7-4ffc-b676-eb9721906504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6192bb01-097f-4989-bf63-fb3d2e5b39ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e308cb7a-cbb3-4496-8a79-06872e44bbb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>8ed64c9f-13ba-4427-9df7-56928f87bbbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>Utilities.TakeOnlyNormalValidInput(this)</value>
      <webElementGuid>7047e1ba-d8bb-4ecf-b81c-aa54c5983eff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bv-field</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>b7eb20c7-9592-410a-a493-9c3044a51d5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Name&quot;)</value>
      <webElementGuid>c350277b-45d5-4d5e-811e-b1144b03045e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Name']</value>
      <webElementGuid>813a660e-ed6e-4fca-be77-6c2ffc0e40ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='insertDiv']/div/div/div/div/div[2]/div[2]/input</value>
      <webElementGuid>0124103e-da1c-434c-af67-0e3b95b61a5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>7132d946-b882-4dfb-9991-e4279d2a9590</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Name' and @name = 'Name' and @type = 'text' and @placeholder = 'Name']</value>
      <webElementGuid>dfce7449-117c-4a74-81c9-814742139b15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
