<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Vendor</name>
   <tag></tag>
   <elementGuidId>c0502fa6-59cb-48ec-8509-89a0a79ed5ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-VendorOrCustomer-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-VendorOrCustomer-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4a5003ee-fc40-42ff-912d-1e2cf64f8737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>9bdf81cd-5588-49cb-94e2-02eb41b8b27d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-VendorOrCustomer-container</value>
      <webElementGuid>52ffa06d-4f09-41cc-b846-e22439f3de48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>b1890b81-2c15-4e11-a310-3157d055708d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f7f18790-e97e-494e-97f8-6b50091607f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Vendor</value>
      <webElementGuid>d8883bf2-eca3-4f2a-ba48-b03432e6e2de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Vendor</value>
      <webElementGuid>d75acc78-9cf5-47d5-9763-9088b63a04eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-VendorOrCustomer-container&quot;)</value>
      <webElementGuid>05b1b3f2-14e4-4e83-8154-bf9f70a25e59</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-VendorOrCustomer-container']</value>
      <webElementGuid>2e06aa35-31b6-410b-9bfa-6605aed5b05b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FormVendor']/div/div[2]/div[3]/div/div/div[2]/span/span/span/span</value>
      <webElementGuid>c74fe506-43f0-4442-9f95-e65e551776b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::span[4]</value>
      <webElementGuid>e9c73b76-5dca-40e5-94ca-4ada2792cddd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please Select'])[1]/preceding::span[3]</value>
      <webElementGuid>08d3f64c-8d87-4885-9fcd-03a48c68bcab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>9d60e2db-5c9c-403c-83ec-7f7b527b2449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-VendorOrCustomer-container' and @title = 'Vendor' and (text() = 'Vendor' or . = 'Vendor')]</value>
      <webElementGuid>e4817cf7-8410-49be-ae34-235a72105b5d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
