<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ul_Please Select State or ProvinceAzad Jamm_b067ff</name>
   <tag></tag>
   <elementGuidId>44217cc4-9b0c-4500-aa21-04b0577a5f72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-StateOrProvinceId-results</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='select2-StateOrProvinceId-results']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
      <webElementGuid>4d021e01-593c-455f-9056-b953d91da980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__options</value>
      <webElementGuid>db3aefe1-cd79-4410-9848-f413ec3fab28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>88444c18-a9ab-41d3-9423-0d601e814b2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-StateOrProvinceId-results</value>
      <webElementGuid>222f1f72-3042-474b-b345-5f3181b9e251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1d768088-ee70-4425-8bfa-00275397257f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8eabcfd1-8627-4511-8ab9-a852f2a31400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please Select State or ProvinceAzad Jammu &amp; KashmirAzad KashmirBalochistanBalochistanFederally Administered Northern Areas/ FANAFederally Administered Tribal Areas/ FATAFederally Administered Tribal Areas/FATAGilgit BaltistanIslamabad Capital TerritoryKhyber PakhtunkhwaKhyber PakhtunkhwaPunjabSindhUnknown</value>
      <webElementGuid>72562983-b028-4dd0-82ff-0ae9114146d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-StateOrProvinceId-results&quot;)</value>
      <webElementGuid>c9f8c6bb-86c2-4187-8128-9bfcd1339fa1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//ul[@id='select2-StateOrProvinceId-results']</value>
      <webElementGuid>fc4342c8-a10e-4d4c-ad41-a83a98dcedae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'select2-StateOrProvinceId-results', '&quot;', ')')])[1]/following::ul[1]</value>
      <webElementGuid>7d8c1825-b140-459a-95db-b9b64fd3c181</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Set Waiting Time'])[1]/following::ul[1]</value>
      <webElementGuid>de5a729c-7e56-4bd2-a914-a7c6ea0f52be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/ul</value>
      <webElementGuid>fdeb993a-f7ed-44fa-a92f-73c2a3ad61ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ul[@id = 'select2-StateOrProvinceId-results' and (text() = 'Please Select State or ProvinceAzad Jammu &amp; KashmirAzad KashmirBalochistanBalochistanFederally Administered Northern Areas/ FANAFederally Administered Tribal Areas/ FATAFederally Administered Tribal Areas/FATAGilgit BaltistanIslamabad Capital TerritoryKhyber PakhtunkhwaKhyber PakhtunkhwaPunjabSindhUnknown' or . = 'Please Select State or ProvinceAzad Jammu &amp; KashmirAzad KashmirBalochistanBalochistanFederally Administered Northern Areas/ FANAFederally Administered Tribal Areas/ FATAFederally Administered Tribal Areas/FATAGilgit BaltistanIslamabad Capital TerritoryKhyber PakhtunkhwaKhyber PakhtunkhwaPunjabSindhUnknown')]</value>
      <webElementGuid>7148319e-c52c-4b95-968e-faa2e70d4b1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
