<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Please enter less than 3 characters_O_297abb</name>
   <tag></tag>
   <elementGuidId>acc6b6a2-43e3-4c1d-bd73-fd5c5f653b19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ObtainedMaxMarks']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ObtainedMaxMarks</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>09fb11b3-06df-4932-ba8f-6842f90d0d9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ObtainedMaxMarks</value>
      <webElementGuid>15737b6e-137b-4ec2-8f38-5e594a6960af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ObtainedMaxMarks</value>
      <webElementGuid>f01dfb96-b175-4da3-9204-431044aaf604</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e49948a5-ce9d-4bfb-a279-32c5fb727aba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Max Range</value>
      <webElementGuid>e7f6097f-856c-4da5-9675-81c2c0a708d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>858a3b4f-8349-4177-b857-58e289c94ec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>Utilities.TakeOnlyInputNumbersWithHyphen(event)</value>
      <webElementGuid>4133aff1-3116-420e-a1a0-b8d41221a81c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bv-field</name>
      <type>Main</type>
      <value>ObtainedMaxMarks</value>
      <webElementGuid>85d8db14-4585-4a64-868e-27b8963b5606</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ObtainedMaxMarks&quot;)</value>
      <webElementGuid>13803e46-a9a4-4287-9c3e-13e218d59961</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ObtainedMaxMarks']</value>
      <webElementGuid>8dccd548-e0b4-40e5-9e6c-58c400ba2775</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AddDivId']/div[2]/div/div/div[3]/div/div[4]/input</value>
      <webElementGuid>a2bd0328-f57a-45b5-8f67-4d03a424271a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>cf663045-0194-4a05-a857-2c5bc032d314</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ObtainedMaxMarks' and @name = 'ObtainedMaxMarks' and @placeholder = 'Max Range']</value>
      <webElementGuid>eae3bda1-e0e7-4a55-95fc-03c8b3a03542</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
