<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Search Item</name>
   <tag></tag>
   <elementGuidId>fb57dadd-7a26-4630-a365-35f17ee87ae6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-NewMedicineName-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-NewMedicineName-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2062b82e-53d8-4d31-8f6d-2373aa29aaec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>85db9901-6872-49a3-b924-ffb08ae68a07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-NewMedicineName-container</value>
      <webElementGuid>9b1f23c5-fe18-4a0e-b3a7-3e2640d6a30d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>09cf8f1b-9706-48b5-8794-d126a9d4fb27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bde7fef0-c6b8-48f3-b52f-9b9cfe4f3533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Search Item</value>
      <webElementGuid>9d35aaf6-bbd6-448a-99c1-22fcb8b9a7fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search Item</value>
      <webElementGuid>a826d06e-6981-4429-a117-92c14f19bb6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-NewMedicineName-container&quot;)</value>
      <webElementGuid>baba8231-c073-4302-a8b7-5eb6273c25c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-NewMedicineName-container']</value>
      <webElementGuid>8b884f41-5667-4b8a-bd5f-65cea23935e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='ManualInventory']/div[3]/div/div/div[2]/span/span/span/span</value>
      <webElementGuid>ece1178a-2aef-4c7c-8a70-b549c7132b4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::span[4]</value>
      <webElementGuid>989eea36-0bf5-4f87-b29e-b4b3759ce1b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please Select Item'])[1]/preceding::span[3]</value>
      <webElementGuid>fa304e51-1995-4240-a35d-a01dead1ddb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/span/span/span/span</value>
      <webElementGuid>6aa81028-3258-4118-955b-28694327e9a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-NewMedicineName-container' and @title = 'Search Item' and (text() = 'Search Item' or . = 'Search Item')]</value>
      <webElementGuid>bc96ed9e-a882-4b7b-881f-cd4068555621</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
