<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Testing_glyphicon glyphicon-edit</name>
   <tag></tag>
   <elementGuidId>3cf4c646-fe6d-4cf2-996e-a524b477a256</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.glyphicon.glyphicon-edit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='BankTable']/tbody/tr/td[7]/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>f1b3aed8-7ce0-4bc2-82c9-4ef9232c26f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>glyphicon glyphicon-edit</value>
      <webElementGuid>521cec2a-192c-4a85-a120-9a17871ab70f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BankTable&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;text-center&quot;]/a[@class=&quot;Action Update btn btn-sm btn-clean btn-icon btn-icon-md&quot;]/i[@class=&quot;glyphicon glyphicon-edit&quot;]</value>
      <webElementGuid>b7cbe3c4-7186-4e9f-a3a1-a9fddeda69a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='BankTable']/tbody/tr/td[7]/a/i</value>
      <webElementGuid>bd4986c0-2c2a-4b5f-9045-069c4541b027</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/a/i</value>
      <webElementGuid>cb0676a6-8f18-4867-b1da-cfa2e85e781b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
