<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__InsertCodetxt</name>
   <tag></tag>
   <elementGuidId>5b1ce316-eea9-45c1-8daa-e48ccb2a307d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#InsertCodetxt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='InsertCodetxt']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ac1b49f0-5d4e-4d66-bb96-9bf4703133f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>InsertCodetxt</value>
      <webElementGuid>dff994c2-7248-4725-9c58-5329e8087c22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>InsertCodetxt</value>
      <webElementGuid>221a4991-e4d0-40c1-82e6-d05eaaa4ff09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>af9f4724-9709-4955-9ca8-2b30ce6dda85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>7ab03208-ecc5-45a3-aef5-57bbf5a1f55c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Code</value>
      <webElementGuid>bd85d735-5d0c-44df-a2dc-9a03d26cbe85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>Utilities.TakeOnlyNormalValidInput(this)</value>
      <webElementGuid>bf345f26-2042-48d2-86b8-dd0587e27c52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bv-field</name>
      <type>Main</type>
      <value>InsertCodetxt</value>
      <webElementGuid>576c585a-095b-4906-b941-a594788b7b50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;InsertCodetxt&quot;)</value>
      <webElementGuid>8d2d1a66-41b0-4040-a576-496baf383b5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='InsertCodetxt']</value>
      <webElementGuid>8b6c8c21-6bcd-4575-89e8-ed5880ef4337</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='insertDiv']/div[2]/div/div/div[3]/div/div[4]/input</value>
      <webElementGuid>d5f243e4-b146-43dc-8ec9-109401c7c369</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>2cec3e24-2ac7-41e9-a53e-31c934dde322</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'InsertCodetxt' and @name = 'InsertCodetxt' and @type = 'text' and @placeholder = 'Code']</value>
      <webElementGuid>c9f9d1f9-da26-49c7-8652-e1addfa0a3dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
