<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select_1</name>
   <tag></tag>
   <elementGuidId>8d196e75-5940-4d30-a93b-571463eadb6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-EmployeeBillTypeId-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-EmployeeBillTypeId-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>44a89077-a3b2-43bd-b230-c8a8dbbaeb90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>0acafa26-ae7e-4f7f-9a20-02cabf8979eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-EmployeeBillTypeId-container</value>
      <webElementGuid>f8f9fb61-7ed5-4990-bfd5-13bc37a0be58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>79c6f76b-304c-45cc-9421-c996948cc4be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1729e182-04b2-4c39-a5cd-38a6e1bc34e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Select </value>
      <webElementGuid>cb2d7464-7be7-4e12-bd18-7527ae9e67eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select </value>
      <webElementGuid>0363e590-8b6d-4851-89ce-554da38d2615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-EmployeeBillTypeId-container&quot;)</value>
      <webElementGuid>69659c68-fb1a-4132-9f81-c730fffed2e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-EmployeeBillTypeId-container']</value>
      <webElementGuid>4e1e9291-4c8d-46d9-831f-a342335e0c08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='EmpBillingForm']/div[4]/div/div/div[2]/span/span/span/span</value>
      <webElementGuid>9c4ca4f6-cabf-4f8c-9b89-84127cc1c5f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::span[4]</value>
      <webElementGuid>c353b8a5-e27d-45dc-9340-a291c3631e79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please Select Bill Type'])[1]/preceding::span[3]</value>
      <webElementGuid>58785773-aebb-4a8c-a007-b45a5600687f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='File'])[1]/preceding::span[3]</value>
      <webElementGuid>9fe76c9e-7d48-4135-b838-715c25b028f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/span/span/span/span</value>
      <webElementGuid>9d4c79cc-0e33-497b-a2dd-802f0ecf0837</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-EmployeeBillTypeId-container' and @title = 'Select ' and (text() = 'Select ' or . = 'Select ')]</value>
      <webElementGuid>ca2c9505-25ae-4ad1-a9bd-499a5a418a30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
