<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Bed_btnCloseBedModal</name>
   <tag></tag>
   <elementGuidId>44cde5cb-f995-4c31-812f-8b4c271c1fa2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnCloseBedModal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnCloseBedModal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>30110ad1-0cfc-42e0-a4a4-05ed2fcd3936</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c07d1538-0428-4b4c-bfa0-95024efaa72b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnCloseBedModal</value>
      <webElementGuid>adcf9725-1d14-4d2a-aa0c-42738a3ef9d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>close</value>
      <webElementGuid>93826cc9-7ef0-43e3-a40c-b29648c7c30b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f03f3621-42a7-4abb-b697-e51dd4c41e03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnCloseBedModal&quot;)</value>
      <webElementGuid>e9d148fc-b519-4ae4-859b-2e8478eccd1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnCloseBedModal']</value>
      <webElementGuid>d0c45c2c-9a27-4bd8-bff7-f957529e6f6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='BedAllocationModal']/div/div/div/div/button</value>
      <webElementGuid>7f23d816-f94f-471c-955d-5cb7509f4a1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[38]/div/div/div/div/button</value>
      <webElementGuid>b58e927d-b8c8-4df0-bb4a-3137e738685f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btnCloseBedModal']</value>
      <webElementGuid>2b6db422-8277-4ed5-8268-d843e8d4545c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
