<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Voucher Description_VoucherDescription</name>
   <tag></tag>
   <elementGuidId>e37c35bc-9f8d-4fa8-96e6-c83505cd5a4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#VoucherDescription</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='VoucherDescription']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>04e057eb-0e98-432d-a30c-53ad47c1abca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>VoucherDescription</value>
      <webElementGuid>b19899bc-7ebc-40ca-adef-0dfc3aab08a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>VoucherDescription</value>
      <webElementGuid>6ee02f1d-1c72-4c41-a277-a80b86a5512e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b383557f-a802-4811-9340-8d6a2df26e6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>0d6e4ee5-04bd-49ba-a613-93743534528e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Voucher Description</value>
      <webElementGuid>b5162801-779d-40ef-9e3c-e32226f789da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;VoucherDescription&quot;)</value>
      <webElementGuid>4f4b62e4-a7e0-42ac-aa6b-07e056122d38</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='VoucherDescription']</value>
      <webElementGuid>dd7dbd55-9e4b-4304-91e7-05746b2a7514</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='MainJVForm']/div/div[2]/div/div/textarea</value>
      <webElementGuid>a37d8531-1f70-4f55-bee9-229d0d1e2acd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>e3bbda59-8690-4789-a836-9de4e55e912f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'VoucherDescription' and @name = 'VoucherDescription' and @type = 'text' and @placeholder = 'Voucher Description']</value>
      <webElementGuid>8c5bec14-1873-4093-b6c3-2c329a149a82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
