<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Address</name>
   <tag></tag>
   <elementGuidId>9642c62e-cfac-4182-ad62-2cbf58254f58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AddressNew</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AddressNew']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dc0c3498-3522-492a-a4a4-623404ef6af2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AddressNew</value>
      <webElementGuid>bebeee5c-42ef-4881-ac19-04505c21be41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dbb2e908-a035-4c1b-833f-92abfa9be227</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Address</value>
      <webElementGuid>9a08e772-d75f-4711-a686-8576ca17d65e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6958bfb3-a646-462b-be1e-4f585638565d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Address</value>
      <webElementGuid>c2891ef2-3c08-4b3a-bd32-c6535ebf4afb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bv-field</name>
      <type>Main</type>
      <value>Address</value>
      <webElementGuid>e6a2fa9a-69f2-4102-8331-4c1e6d178356</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AddressNew&quot;)</value>
      <webElementGuid>0b9f0cbb-0d2e-4485-81e3-1bf67e823cc1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AddressNew']</value>
      <webElementGuid>e11cf97c-0323-459c-9647-5f4976740836</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='UserEducationDatatableDiv']/div[2]/div/div[6]/div[2]/div[2]/input)[2]</value>
      <webElementGuid>0ea49c19-aa23-4c8a-98e4-16917c602420</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[6]/div[2]/div[2]/input</value>
      <webElementGuid>6c52d356-e8e8-4f03-b84c-f8f898607148</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'AddressNew' and @type = 'text' and @name = 'Address' and @placeholder = 'Address']</value>
      <webElementGuid>63b77082-b364-4006-8694-614a3fbff009</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
