<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_PDF</name>
   <tag></tag>
   <elementGuidId>ec06faaf-c5ed-41e6-a7d1-6bd88980ee4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='BtnGetReportPdf']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#BtnGetReportPdf</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>44852ae9-3b9c-49a5-bad2-f977db150957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>aeef5371-0031-4108-bd2b-82222ba983e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BtnGetReportPdf</value>
      <webElementGuid>6411e214-d889-4a5e-a265-c243d8c0766c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn btn-default</value>
      <webElementGuid>fd251072-ea0c-40d9-952a-885f1b13639d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>   PDF</value>
      <webElementGuid>3e6e3674-8b0a-47b4-a6f4-1efb4d626c51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BtnGetReportPdf&quot;)</value>
      <webElementGuid>25f1a4b2-7141-4fbd-987d-9d870e1f1495</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='BtnGetReportPdf']</value>
      <webElementGuid>bf600a4e-b25a-4d3f-85cf-8d0aca800c61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_content']/div/div[3]/div[2]/div/div/div/div/div/div/button</value>
      <webElementGuid>15ca5606-be32-4879-8458-2373d95200f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chart Of Accounts'])[4]/following::button[1]</value>
      <webElementGuid>67bf3c3a-bcc4-4a02-8a8d-02601690424e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/following::button[1]</value>
      <webElementGuid>3f288706-dc9c-48c4-b8af-8554823d9f62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div/div/div/div/button</value>
      <webElementGuid>4a3ec86b-0d80-4487-80aa-a42896090b7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'BtnGetReportPdf' and (text() = '   PDF' or . = '   PDF')]</value>
      <webElementGuid>569290a9-a159-4dd3-b23f-09cea1d24917</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
