<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ul_Select ScalesBPS-1BPS-10BPS-11BPS-12BPS-_f72f2c</name>
   <tag></tag>
   <elementGuidId>e875e5e9-122c-4fc8-8b93-bd54793393c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='select2-ScaleID-results']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-ScaleID-results</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
      <webElementGuid>e1d22a07-bc1c-44b1-8276-131e31ca2688</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__options</value>
      <webElementGuid>371e7109-d670-4ae7-a66d-6e1498245368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>931f6a98-4e1a-40bb-bcb1-87e03c460b6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-ScaleID-results</value>
      <webElementGuid>d0fba831-92c7-4b3e-9f0d-bb82fa40331f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>15b645a2-7a44-4155-8e6d-b8e5edb4b26a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1788522a-f14f-4727-bc7b-993aafadb1cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select ScalesBPS-1BPS-10BPS-11BPS-12BPS-13BPS-14BPS-15BPS-16BPS-17BPS-18BPS-19BPS-2BPS-20BPS-21BPS-22BPS-3BPS-4BPS-5BPS-6BPS-7BPS-8BPS-9H/CaptLumsumMP-IITest-1Testing M</value>
      <webElementGuid>cd96a046-870f-4a80-ba4a-ed48182702e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-ScaleID-results&quot;)</value>
      <webElementGuid>dfd4a67b-18a9-4751-8fcf-31b5fe0563fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//ul[@id='select2-ScaleID-results']</value>
      <webElementGuid>b445283d-d501-447b-b6d1-a49e5008ca4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'select2-ScaleID-results', '&quot;', ')')])[1]/following::ul[1]</value>
      <webElementGuid>db2d695d-9835-4bb5-9c1f-23954e2c27bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Set Waiting Time'])[1]/following::ul[1]</value>
      <webElementGuid>02d2f1ed-706e-4851-9054-f89d3157eb01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/ul</value>
      <webElementGuid>f35b1bd6-a1ae-4f4e-b462-a211aba24c61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ul[@id = 'select2-ScaleID-results' and (text() = 'Select ScalesBPS-1BPS-10BPS-11BPS-12BPS-13BPS-14BPS-15BPS-16BPS-17BPS-18BPS-19BPS-2BPS-20BPS-21BPS-22BPS-3BPS-4BPS-5BPS-6BPS-7BPS-8BPS-9H/CaptLumsumMP-IITest-1Testing M' or . = 'Select ScalesBPS-1BPS-10BPS-11BPS-12BPS-13BPS-14BPS-15BPS-16BPS-17BPS-18BPS-19BPS-2BPS-20BPS-21BPS-22BPS-3BPS-4BPS-5BPS-6BPS-7BPS-8BPS-9H/CaptLumsumMP-IITest-1Testing M')]</value>
      <webElementGuid>182e5ed2-194a-4331-a755-c2d3f9ee3c04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
