<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Credit_FormCreditAmount</name>
   <tag></tag>
   <elementGuidId>01d3626e-1cf0-4432-967f-72cddc2ba438</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='FormCreditAmount']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#FormCreditAmount</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>340097e0-2b3b-4b5d-a680-c813c3c41234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b1cb979a-a5b2-4e77-ad97-9faa9973532b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7a4b8cce-b984-4b7a-b166-fc0dedc4fe9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FormCreditAmount</value>
      <webElementGuid>cf338ac7-65f4-4ff1-98a7-68d6632bd586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return isNumberKeyCredit(event)</value>
      <webElementGuid>cb844c76-6a6b-4918-a879-231c4ad43b25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FormCreditAmount</value>
      <webElementGuid>55c9b4a3-2fa5-4d03-b6a9-082589b1cbef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>63ad861f-2ad0-403c-a256-31525dc34adf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>87739273-0685-4283-995a-21d08876412c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Credit</value>
      <webElementGuid>48b97c42-c86e-4dbe-be1c-700a8fd1613b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>527450ae-eae2-4b47-b17f-c72e8f30b0d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bv-field</name>
      <type>Main</type>
      <value>FormCreditAmount</value>
      <webElementGuid>1728d344-1244-4350-a3b5-80eb36744d46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FormCreditAmount&quot;)</value>
      <webElementGuid>2b21c0d5-2e50-48f6-b606-b191dddb46d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='FormCreditAmount']</value>
      <webElementGuid>5ade3275-2a68-4594-9b54-eab40a009e3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='JvForm']/div/div/div[3]/div/div/input</value>
      <webElementGuid>4afad363-5e3e-4ee6-a971-e840f30076b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>f6d5d7fe-244c-42c4-9941-eaa82242f452</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'FormCreditAmount' and @name = 'FormCreditAmount' and @type = 'number' and @placeholder = 'Credit']</value>
      <webElementGuid>97b56b50-52be-46a3-b7ec-906f26a5f3bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
