<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__CellNumber</name>
   <tag></tag>
   <elementGuidId>8368baf2-e84d-447c-aba8-0589e42e9b30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CellNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CellNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6647503a-9d48-4b4e-a51d-16bdc57c6358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CellNumber</value>
      <webElementGuid>5b735537-a7fc-487c-aeb8-3d52bb27dfb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5fae0d39-681c-49d5-905f-5470389672bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CellNumber</value>
      <webElementGuid>5a94e32a-dfbc-4e58-ba42-8ff958089cee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>5e76476c-7af8-4d1a-89a7-1ff9dbfa3be0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>76821c73-aabc-4e22-bf15-9c1dbafe779b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>5f059944-652e-4a45-a485-cc43df5a6f86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>03001234567</value>
      <webElementGuid>33f1afbd-d2fa-4d54-be89-eaa63feb15ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>IS_iNTT(this)</value>
      <webElementGuid>7c3ea898-5bb4-47d2-ac85-49973c9c400d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bv-field</name>
      <type>Main</type>
      <value>CellNumber</value>
      <webElementGuid>396cdc2a-407b-4884-b26b-29fa516a3100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CellNumber&quot;)</value>
      <webElementGuid>fa4520bc-afd4-4cda-bd16-277f045a19f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CellNumber']</value>
      <webElementGuid>123598cf-1587-42dd-9a6b-f9da2443b7e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UserEducationDatatableDiv']/div[2]/div/div[7]/div/div[2]/input</value>
      <webElementGuid>470f1231-7a44-48c0-a278-1018d34e3392</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div[2]/input</value>
      <webElementGuid>99066352-c165-4ead-aef4-9d97368f8ab5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'CellNumber' and @type = 'text' and @name = 'CellNumber' and @placeholder = '03001234567']</value>
      <webElementGuid>2892e659-4643-436f-b897-7b5f1d189f72</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
