<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Dec 20, 2022 1536_glyphicon glyphicon-edit</name>
   <tag></tag>
   <elementGuidId>de4e2629-5b61-4c02-ae58-555a0a331ec6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='Patients']/tbody/tr/td[6]/a[6]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.glyphicon.glyphicon-edit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>7b86f2cb-5b37-498e-803b-e565f7234ffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>glyphicon glyphicon-edit</value>
      <webElementGuid>5fe9a915-02e8-493d-8b94-9b60496f9c9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Patients&quot;)/tbody[1]/tr[@class=&quot;bg-success-tab-row odd&quot;]/td[@class=&quot;RowActions text-center&quot;]/a[@class=&quot;UpdateModalForArmedForces  btn btn-sm btn-clean btn-icon btn-icon-md&quot;]/i[@class=&quot;glyphicon glyphicon-edit&quot;]</value>
      <webElementGuid>8336f6f2-ad2d-4087-afd3-504ee49d8973</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='Patients']/tbody/tr/td[6]/a[6]/i</value>
      <webElementGuid>f3e1497b-fd7e-4b41-ab8a-171de45c22b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[6]/i</value>
      <webElementGuid>2be799ef-5179-40c0-905b-85b428171e44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
