<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Dr. Aasifa Siddiqa_GenerateReport</name>
   <tag></tag>
   <elementGuidId>a3e73a4a-be2c-49f2-a679-49c5541a8c65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='GenerateReport']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#GenerateReport</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e2bbd513-8593-4010-a2e1-b7e22628e6e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GenerateReport</value>
      <webElementGuid>48b61a77-14f5-4153-aff3-0db3a1aec565</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>68b42717-59c6-415e-ad22-3fff4c6346a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Generate Report</value>
      <webElementGuid>b0add085-0f73-4a55-90f3-fc4418965307</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary pull-right</value>
      <webElementGuid>cf881b95-83a8-46c7-81f0-8995b8bc9609</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GenerateReport&quot;)</value>
      <webElementGuid>e970fe9b-27a8-4bdd-940a-2c18894eae13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='GenerateReport']</value>
      <webElementGuid>9975a0b1-6941-437d-8eb4-4a9e1e03cb3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AddDivId']/div[3]/div/div/div[2]/input</value>
      <webElementGuid>e15bf71e-29c0-446b-85ee-906eff698fff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>00e4e7fc-8ae1-40bc-be83-978cec3421ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'GenerateReport' and @type = 'button']</value>
      <webElementGuid>71e000ef-4587-430b-904a-c0d8c047a795</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
