<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_All MiscServices Free</name>
   <tag></tag>
   <elementGuidId>9de9c925-764d-4eaf-b319-650a738d6c8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='IndividualPackageForm']/div[8]/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>5b3eb0a3-01a4-4461-b699-9764eee73c3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>IsAllMiscServicesFree</value>
      <webElementGuid>45d760a1-6ab8-4947-a0a3-7cd61dcec1aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All MiscServices Free</value>
      <webElementGuid>92d9102c-266a-454a-a847-9ba7f4929e3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IndividualPackageForm&quot;)/div[@class=&quot;form-group row&quot;]/div[@class=&quot;col-md-2&quot;]/label[1]</value>
      <webElementGuid>8240ae6d-2815-4ef6-92ba-6baf78fb9111</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='IndividualPackageForm']/div[8]/div/label</value>
      <webElementGuid>bfcae49c-eb81-4625-82de-2fbe2d7d6b66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Consultancy Free'])[1]/following::label[2]</value>
      <webElementGuid>b712a197-51a6-4f90-9a06-a5e189755f8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All SubServices Free'])[1]/following::label[4]</value>
      <webElementGuid>a6a61e7a-a77e-4009-a076-a57ad80a8d11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::label[2]</value>
      <webElementGuid>9f17e332-e11f-4261-bcd8-88a7edaab20a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Packages'])[3]/preceding::label[2]</value>
      <webElementGuid>d0a47446-81e6-47fb-9e01-bf39960b6808</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='All MiscServices Free']/parent::*</value>
      <webElementGuid>73a14aa2-9f38-428d-acfa-204b7cafc572</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/label</value>
      <webElementGuid>e7282a4b-0a56-4703-a783-dfc9fb537d19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'All MiscServices Free' or . = 'All MiscServices Free')]</value>
      <webElementGuid>3c2f1383-9fe6-477f-954c-e17f39ce291d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
