<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Please Enter Password_UpdateBtn</name>
   <tag></tag>
   <elementGuidId>10e1758c-8def-48de-8e0d-15f3e44aa9c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UpdateBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UpdateBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6b20dc47-0d7c-4380-a7d3-fe94fc6c7e97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UpdateBtn</value>
      <webElementGuid>cc3c6036-cd5b-46c2-ac43-fe0f55192f27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>7a163a06-d90f-4edd-b499-56b059526bcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>cdd03934-d0c3-45e5-8d3f-43f48fc8b9f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>3e0c643a-0554-47e1-836d-63e1a0dcb817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UpdateBtn&quot;)</value>
      <webElementGuid>8f57f7fc-31da-4132-83d1-e12ea7b5f3ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UpdateBtn']</value>
      <webElementGuid>39cceee0-ccf1-4cba-afb6-c351b801b268</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AddDivId']/div[3]/div/div[2]/div/div/input[2]</value>
      <webElementGuid>45e604f5-a8f8-413d-b578-2a7c0c25456e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>a2fc2192-5767-4268-9c7a-56ac4f682286</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'UpdateBtn' and @type = 'submit']</value>
      <webElementGuid>d77506c9-7116-40aa-bb6d-5137614e64e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
