<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Pakistan Army</name>
   <tag></tag>
   <elementGuidId>29725246-5274-41f0-bd3b-579a1bec0fd6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='select2-PanelOrganizationId-result-y9m6-94147ae5-8c52-462a-80ba-8cc7a0d0ac3f']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-PanelOrganizationId-result-y9m6-94147ae5-8c52-462a-80ba-8cc7a0d0ac3f</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>c94dd169-4670-419d-b5a7-f05baf08cb5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--highlighted</value>
      <webElementGuid>fb9a57c0-efbc-4bf6-a78e-32f47fb5a54a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-PanelOrganizationId-result-y9m6-94147ae5-8c52-462a-80ba-8cc7a0d0ac3f</value>
      <webElementGuid>e960d936-8a86-48e0-adb2-02ceb55d01d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>5caac847-fe77-4e59-9331-42f4e1023e58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>66df112b-721d-4ab9-9d89-b0ad76e2f5af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select2-id</name>
      <type>Main</type>
      <value>select2-PanelOrganizationId-result-y9m6-94147ae5-8c52-462a-80ba-8cc7a0d0ac3f</value>
      <webElementGuid>d1a20507-7e05-4cc4-8689-5aa1e3aac151</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pakistan Army</value>
      <webElementGuid>33431721-4629-442d-966f-b9112f5c5c55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-PanelOrganizationId-result-y9m6-94147ae5-8c52-462a-80ba-8cc7a0d0ac3f&quot;)</value>
      <webElementGuid>21266851-c40c-4f28-add7-f4897c09a9eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='select2-PanelOrganizationId-result-y9m6-94147ae5-8c52-462a-80ba-8cc7a0d0ac3f']</value>
      <webElementGuid>45cde988-3158-432d-ae41-67d46af1e262</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select2-PanelOrganizationId-results']/li</value>
      <webElementGuid>c78c3068-9ecb-4d2a-9bbd-91ad48d1d9cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::li[1]</value>
      <webElementGuid>ec67af18-19be-43f8-8089-738082ada377</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[2]/following::li[1]</value>
      <webElementGuid>5175761c-9b74-409f-a907-3093caa7b284</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/ul/li</value>
      <webElementGuid>5806c876-a9b7-4a1f-875f-1ed6a7d6fc8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-PanelOrganizationId-result-y9m6-94147ae5-8c52-462a-80ba-8cc7a0d0ac3f' and (text() = 'Pakistan Army' or . = 'Pakistan Army')]</value>
      <webElementGuid>b4fe2e7e-6888-449b-9607-20e5942f3f6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
