<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__OnPanelEmployeeNo</name>
   <tag></tag>
   <elementGuidId>11a0519c-d26c-4ed1-86b6-aabcefb62f5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='OnPanelEmployeeNo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#OnPanelEmployeeNo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>af4b4290-f66c-4121-97b2-90f4c431fbf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>OnPanelEmployeeNo</value>
      <webElementGuid>7411f8b1-aea0-4789-981c-1265c8c8a326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3041d84d-539e-46e4-90d4-004d4de4efb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>OnPanelEmployeeNo</value>
      <webElementGuid>a1db2b80-0c81-4f55-b59f-f2090574d799</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>84aba912-cd7f-4d20-a01c-0ab2ba66c38b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bv-field</name>
      <type>Main</type>
      <value>OnPanelEmployeeNo</value>
      <webElementGuid>5a7e8edf-df86-40e5-874a-6969b47c1e1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OnPanelEmployeeNo&quot;)</value>
      <webElementGuid>f5d4eb70-2f8b-4b9a-a49e-d7a0733f2a08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='OnPanelEmployeeNo']</value>
      <webElementGuid>c70e373b-de15-4302-9bba-7290cb6fca94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SelfDisplayOnPanel']/div[2]/div/div[2]/input</value>
      <webElementGuid>d7c80444-3507-477b-b78b-8bd8b5c248df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/div[2]/input</value>
      <webElementGuid>e7def262-124c-4f68-b16e-d20ddd8a028b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'OnPanelEmployeeNo' and @type = 'text' and @name = 'OnPanelEmployeeNo']</value>
      <webElementGuid>67e42167-cab6-4f43-801f-a8fcf79f1d83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
