<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__PatientIdentityNo</name>
   <tag></tag>
   <elementGuidId>91a11f89-86c9-49cb-bc39-9df79884f266</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PatientIdentityNo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PatientIdentityNo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6ffac058-5acb-4621-bc1d-e0fa052952e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PatientIdentityNo</value>
      <webElementGuid>5beb4f4c-dfba-465f-b7fc-d93f8478cce5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PatientIdentityNo</value>
      <webElementGuid>ff105ad3-f4cf-4719-97f6-08cedf89636b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>a9ef3cb1-4180-428e-9496-e4beedd6e5a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>98fd5d20-b8e3-49a8-987d-4a0bea503a4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>8b7e8f89-84c4-47e9-9422-71639057e398</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Patient Identity </value>
      <webElementGuid>ab97bcfb-58e5-43f3-9042-c12d13daeec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>Utilities.TakeOnlyNormalValidInput(this)</value>
      <webElementGuid>2b510517-eb77-4f66-9046-d6a2a59edab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>GetPatientDetails()</value>
      <webElementGuid>03b22af0-a022-418b-a297-ec8e64690e83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bv-field</name>
      <type>Main</type>
      <value>PatientIdentityNo</value>
      <webElementGuid>1bf9f61e-c37b-4c68-8cd9-c5e7a9135b2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PatientIdentityNo&quot;)</value>
      <webElementGuid>46e34aed-ff11-4d3d-a48a-fffbd6907ab7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PatientIdentityNo']</value>
      <webElementGuid>db3e6ee8-30ec-41cc-9189-9670e5a7bde6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PatientMRdiv']/div[2]/input</value>
      <webElementGuid>2ecaabe4-aa7b-4a1c-8236-52ba905eb599</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div/div[2]/input</value>
      <webElementGuid>3a561453-e5a7-4ff1-b4a2-92fe4749d0f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PatientIdentityNo' and @name = 'PatientIdentityNo' and @type = 'text' and @placeholder = 'Patient Identity ']</value>
      <webElementGuid>ef6a68e2-91af-45a8-a804-1cba0f9808e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
