<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Academic Affair Store</name>
   <tag></tag>
   <elementGuidId>4b692e7b-fa8b-4543-873e-46edf857ec7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-ListPharmacyStore-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-ListPharmacyStore-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>11222dd7-27b1-4ede-bb14-ae7c619c88ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>f0f52849-af6e-4dc2-be6c-cd1524985f0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-ListPharmacyStore-container</value>
      <webElementGuid>ea3a9fc4-9afb-4165-812a-6afb9a052a0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>fdae8891-ecc5-4d9d-b0b2-b682b50025b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7b00f779-8ff4-4044-9544-c5d1f737d83f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Academic Affair Store</value>
      <webElementGuid>40c67ac4-810e-4f99-a4b9-86cc4d097fd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Academic Affair Store</value>
      <webElementGuid>06e21bf4-bfbf-414b-9262-f47b8701ce1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-ListPharmacyStore-container&quot;)</value>
      <webElementGuid>2c39d33f-1bb2-4b0f-8fbd-5d57082a0b31</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-ListPharmacyStore-container']</value>
      <webElementGuid>fb539de8-3f02-4e7a-8124-4d1f58daffbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_content']/div/div/div[2]/div/div/div[2]/div[2]/span/span/span/span</value>
      <webElementGuid>94bf0009-a4ca-4fdd-847e-9f190f6a67e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Store'])[1]/following::span[4]</value>
      <webElementGuid>a045bf75-496e-45e6-9640-d56d757c6fb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='iHealthCure Medical &amp; Clinical Hospital'])[3]/following::span[6]</value>
      <webElementGuid>dc0c1ab3-3fb6-4060-9209-8fed02ae8426</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stock Type'])[2]/preceding::span[3]</value>
      <webElementGuid>2fee8aee-aaff-48c2-98be-cc98888b60c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[2]/preceding::span[3]</value>
      <webElementGuid>798e97df-9120-47c2-ac38-113280606fcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/span/span/span/span</value>
      <webElementGuid>09e500f8-eaa0-4c89-b317-213b458acbcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-ListPharmacyStore-container' and @title = 'Academic Affair Store' and (text() = 'Academic Affair Store' or . = 'Academic Affair Store')]</value>
      <webElementGuid>b713cbbc-7280-4e2c-969a-f5685f7cfe30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
