<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Dr. Abdul Hadi  Postgraduate Trainee</name>
   <tag></tag>
   <elementGuidId>a667942a-7d2d-45d6-9230-8f39419e4d43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bs-select-1-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='bs-select-1-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>da9b668b-a24f-446b-97b6-40ed5efff1b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>2d170edf-108c-4cc4-abb4-5e607390dbad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item</value>
      <webElementGuid>d94aa248-7072-4c3b-8178-2a77374d9ecb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bs-select-1-1</value>
      <webElementGuid>6147e923-5c0a-4641-aa74-de144110d520</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>bff5bcce-cb52-475c-bef8-4544354901a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-setsize</name>
      <type>Main</type>
      <value>232</value>
      <webElementGuid>c07c9236-e2af-43a3-b639-131ab7957377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-posinset</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>b6a13222-d082-437c-8434-ef7e88be9e71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dr. Abdul Hadi | Postgraduate Trainee</value>
      <webElementGuid>0fb44d90-f69d-4719-a523-08a0b2f5791d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bs-select-1-1&quot;)</value>
      <webElementGuid>b9792a18-812c-484b-af0c-4fd806847e6d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='bs-select-1-1']</value>
      <webElementGuid>f9fa9c0f-205b-4d7d-89b7-ee8550024e9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bs-select-1']/ul/li[2]/a</value>
      <webElementGuid>069c86fd-6316-4dfe-b594-f285e1c98882</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Doctor'])[3]/following::a[1]</value>
      <webElementGuid>63ec318a-8b15-4da8-8297-f2503f24f177</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Doctor'])[2]/following::a[2]</value>
      <webElementGuid>73e079bd-0e86-4032-885e-200e202ae77b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dr. Abdul Malik | Associate Professor Of Paediatric Cardiology'])[2]/preceding::a[1]</value>
      <webElementGuid>90bd335e-7932-43f4-8cfe-5651209332e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[2]/a</value>
      <webElementGuid>6d11f40a-6772-4b36-948c-f3347566db5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'bs-select-1-1' and (text() = 'Dr. Abdul Hadi | Postgraduate Trainee' or . = 'Dr. Abdul Hadi | Postgraduate Trainee')]</value>
      <webElementGuid>ce0e6f89-e8b3-4dc3-aa52-d50f5969415f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
