<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_All Reference Types</name>
   <tag></tag>
   <elementGuidId>9c3952c9-12a7-45f9-a857-304362a5d718</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-RefType-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-RefType-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1e1bb94e-90b8-44a4-bc06-9c633c52f3a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>4b559411-5db2-4db8-bbf9-9124a1ae5d2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-RefType-container</value>
      <webElementGuid>21496ed9-7df4-4fbf-8f5a-458128399f5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>3be103bd-1003-40aa-aff5-2ad6f57c4894</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a1263179-04bd-448a-9f6f-61973c0ff00c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>All Reference Types</value>
      <webElementGuid>03a29d6e-b9a8-42d5-bfda-adc6c7e880f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All Reference Types</value>
      <webElementGuid>0a975275-94ba-48af-b01f-ff8ee924bfc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-RefType-container&quot;)</value>
      <webElementGuid>73d07259-2813-4bad-b190-4d181889374d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-RefType-container']</value>
      <webElementGuid>2764205a-8f28-49fd-8f0c-b6eb147a0dab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_content']/div/div[3]/div[2]/div/div/div[4]/div/span/span/span/span</value>
      <webElementGuid>fb627f6a-0ba1-4d17-ada1-362bd9a4dbb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reference Detail'])[1]/following::span[4]</value>
      <webElementGuid>2f0288ff-0856-4d6f-bbdd-920897f4c4d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADV - Purchase Order Advance'])[2]/following::span[6]</value>
      <webElementGuid>c27fad6a-2c59-4055-ba80-0bb3ea45f6f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Vendor'])[2]/preceding::span[3]</value>
      <webElementGuid>fc568d85-3bd1-49fe-9294-8584efe3ef4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Employee'])[2]/preceding::span[9]</value>
      <webElementGuid>086319a7-de5f-43bd-82eb-9cb70a4d2bb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/span/span/span/span</value>
      <webElementGuid>a1526293-0deb-4fe9-853d-c48db4fbff53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-RefType-container' and @title = 'All Reference Types' and (text() = 'All Reference Types' or . = 'All Reference Types')]</value>
      <webElementGuid>fa87926d-1086-4a0d-adc5-008c968d379d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
