<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Monday                            Tu_4c425c</name>
   <tag></tag>
   <elementGuidId>a553ca0f-3b07-4694-9054-d7d732ef8531</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#WeekDays</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='WeekDays']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b5936278-3651-4bcf-be0d-d94217a249e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>WeekDays</value>
      <webElementGuid>4e4a0f22-51bd-48e2-88c1-9cbca9b68cb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>WeekDays</value>
      <webElementGuid>22218a94-6dfe-4fd3-b9d1-91a4289c01c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectpicker pull-left</value>
      <webElementGuid>7d2f2560-209c-477b-98f4-5df2bc9fe03f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>0d94dff0-a034-474f-8510-55644c96591d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-98</value>
      <webElementGuid>612ab07d-985f-41b1-b232-42ccb4a0f0be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bv-field</name>
      <type>Main</type>
      <value>WeekDays</value>
      <webElementGuid>8de59355-6011-4aa9-ad7c-c71cdbe92bed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Monday
                            Tuesday
                            Wednesday
                            Thursday
                            Friday
                            Saturday
                            Sunday
                        </value>
      <webElementGuid>d19d0248-b493-4e51-8f59-fc00efe33f12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;WeekDays&quot;)</value>
      <webElementGuid>8e8e30d8-5c7c-4efd-bdbf-ddf49aae65cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='WeekDays']</value>
      <webElementGuid>754c6905-c952-41fd-9177-b7142382e898</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AddDivId']/div[3]/div/div[3]/div[2]/div/select</value>
      <webElementGuid>e097f3a6-6493-4cc2-be11-7b56211ca557</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::select[1]</value>
      <webElementGuid>b1a32aa4-5314-46f7-9520-85f136d81447</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monday'])[2]/preceding::select[1]</value>
      <webElementGuid>c67e8ec7-5562-4d24-be71-b384ba30675a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select All'])[1]/preceding::select[1]</value>
      <webElementGuid>15107dab-223d-48b8-a292-d9569239e4d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/select</value>
      <webElementGuid>36e48a3e-21a2-4758-8bbc-bb42195b9a20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'WeekDays' and @name = 'WeekDays' and (text() = '
                            Monday
                            Tuesday
                            Wednesday
                            Thursday
                            Friday
                            Saturday
                            Sunday
                        ' or . = '
                            Monday
                            Tuesday
                            Wednesday
                            Thursday
                            Friday
                            Saturday
                            Sunday
                        ')]</value>
      <webElementGuid>173db44b-195e-44b9-87b6-2ec932972856</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
