<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select</name>
   <tag></tag>
   <elementGuidId>57c5e86f-032b-452c-8708-9fdadee50098</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-InsertDayClosingCashAccountId-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-InsertDayClosingCashAccountId-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>02c9c33d-131e-4379-b50a-b33d3749c834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>0d68ca73-8172-4571-9a2e-ed07beaef6fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-InsertDayClosingCashAccountId-container</value>
      <webElementGuid>9df4b52b-0deb-4343-ad7e-8bb9350b12f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>7aa5f353-8a2c-4b6f-b4c1-ad415ace886e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>080f4dfd-ab69-48d1-93d7-b506be224316</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>26b74974-477d-4fc5-9fad-7052db22eadb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-InsertDayClosingCashAccountId-container&quot;)</value>
      <webElementGuid>cf5a9a6a-8a38-4bcc-bade-b76028124fbf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-InsertDayClosingCashAccountId-container']</value>
      <webElementGuid>d813e764-f646-4a55-b296-8074a5b0ca76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AddDivId']/div[2]/div/div[3]/div[2]/span/span/span/span</value>
      <webElementGuid>9f0243e4-29be-4c25-85f7-73cd95a086b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account'])[1]/following::span[4]</value>
      <webElementGuid>cdd9b06c-669e-43d0-9728-f930b9002c43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please Enter Account Number'])[1]/following::span[4]</value>
      <webElementGuid>d41b7176-2bc1-4cbb-9e49-86818f492ac2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::span[4]</value>
      <webElementGuid>a32d88aa-53bf-4333-8a6b-e4d5ec1b25ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>fb7defa5-4eec-4ff5-9406-f53b3a9d11af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-InsertDayClosingCashAccountId-container' and (text() = 'Select' or . = 'Select')]</value>
      <webElementGuid>5998a6c3-ad78-4bd9-b3d6-5ef5dccc1269</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
