<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Address</name>
   <tag></tag>
   <elementGuidId>41d5b511-6406-4112-9b73-d1513c66c07d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AddressNew</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AddressNew']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7f2bfae7-a4d9-460e-aac5-560f8516c5fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AddressNew</value>
      <webElementGuid>c571495a-7fa3-4261-8041-85faa69fbc7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>85cfbdf2-edc5-4e77-90d4-78456a7f2be9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Address</value>
      <webElementGuid>9e6b695e-ebc3-481b-8dcd-717c0c2fcc22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9c1dfe8e-fc8c-4119-bfa6-2c8d31995990</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Address</value>
      <webElementGuid>17f65784-c7d1-42ee-9a2f-c8ae5637dd06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bv-field</name>
      <type>Main</type>
      <value>Address</value>
      <webElementGuid>09658937-69ce-418b-9766-478f02e6432e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AddressNew&quot;)</value>
      <webElementGuid>257414f3-f474-428d-b975-5f5b0c7aa402</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AddressNew']</value>
      <webElementGuid>d256fb82-b3d2-47cd-960d-312425a6626f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='UserEducationDatatableDiv']/div[2]/div/div[6]/div[2]/div[2]/input)[2]</value>
      <webElementGuid>51ec2f5d-01e8-4ef7-9e58-87d94b9c1a86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[6]/div[2]/div[2]/input</value>
      <webElementGuid>3e6b3b97-7c79-4271-a521-7cbf752e0c9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'AddressNew' and @type = 'text' and @name = 'Address' and @placeholder = 'Address']</value>
      <webElementGuid>065a2327-0757-4f0c-a9b8-d0d085b55ba0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
