<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__CellNumber</name>
   <tag></tag>
   <elementGuidId>aab656bc-3350-4296-92ab-3788ddda8557</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CellNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CellNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d4653544-b488-4dd9-8ee9-6713082616bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CellNumber</value>
      <webElementGuid>ae6222f0-8268-4d4e-b35b-735ed5c27ec9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>155137fe-ef2b-489b-b5f5-b87023a4db92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CellNumber</value>
      <webElementGuid>a3fca72e-dec3-412c-8e95-d70f8d7b2497</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b652f17d-771d-40e8-bd71-e4e2a776755f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>4e953256-39ee-46ff-995e-77344810b9aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>3e97fc65-0338-4029-9f82-450141845ca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>03001234567</value>
      <webElementGuid>b27847f9-61fd-468d-9871-2efb9b2af028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>IS_iNTT(this)</value>
      <webElementGuid>e8434048-ed73-4f1e-a2c7-2c7a869a3acd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bv-field</name>
      <type>Main</type>
      <value>CellNumber</value>
      <webElementGuid>599b4c22-5e04-4127-a890-427d82f58460</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CellNumber&quot;)</value>
      <webElementGuid>5a53e480-f2c1-4432-a11a-1ea1f2eec06f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CellNumber']</value>
      <webElementGuid>4da4706d-34ac-4d44-afb8-cb8febcb3fac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UserEducationDatatableDiv']/div[2]/div/div[7]/div/div[2]/input</value>
      <webElementGuid>efccc399-c88e-435c-8576-54d63d31fc87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div[2]/input</value>
      <webElementGuid>de58d68d-8b74-4480-b640-2fc8c3b38159</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'CellNumber' and @type = 'text' and @name = 'CellNumber' and @placeholder = '03001234567']</value>
      <webElementGuid>d0dfbdc8-27f0-41a7-9611-d31c71f5b893</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
