<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ul_Select BuildingAzeemFirst FloorGround Fl_6b6978</name>
   <tag></tag>
   <elementGuidId>0d568733-1851-4e24-bd40-99696fb2555d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='select2-BuildingId-results']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-BuildingId-results</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
      <webElementGuid>d97af220-eff4-415c-870e-04b306139274</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__options</value>
      <webElementGuid>22eea79e-d467-4941-9742-855b1cece468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>704b3ddd-180f-4799-884d-88414498bc20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-BuildingId-results</value>
      <webElementGuid>4594a4c5-38b3-4f3d-bb75-42f76c234c24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>65161e88-6ae5-48af-9ce5-1a5d95551d9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0feb3c9b-2d3b-41c8-ba1f-cb9d6cad697e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select BuildingAzeemFirst FloorGround FloorHassanModel PharmacyRawalpindi Institute Of CardiologySgfgdfShaikh Muhammad Bin Zayed Al Nahyan Institute Of CardiologyTesting M</value>
      <webElementGuid>079e6463-6503-4cab-bb56-a5864ae2fa03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-BuildingId-results&quot;)</value>
      <webElementGuid>43b79e88-8313-445a-80ba-d52ea24f6a5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//ul[@id='select2-BuildingId-results']</value>
      <webElementGuid>5fbc5a70-2a62-4b26-a696-6bb23422751c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'select2-BuildingId-results', '&quot;', ')')])[1]/following::ul[1]</value>
      <webElementGuid>792c06a5-d58e-4b84-b1ce-26cb18914387</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Set Waiting Time'])[1]/following::ul[1]</value>
      <webElementGuid>8d733d0d-b309-43eb-8f45-1cbcdebdf6ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/ul</value>
      <webElementGuid>e5732d05-9207-4402-a4c7-8641db8878c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ul[@id = 'select2-BuildingId-results' and (text() = 'Select BuildingAzeemFirst FloorGround FloorHassanModel PharmacyRawalpindi Institute Of CardiologySgfgdfShaikh Muhammad Bin Zayed Al Nahyan Institute Of CardiologyTesting M' or . = 'Select BuildingAzeemFirst FloorGround FloorHassanModel PharmacyRawalpindi Institute Of CardiologySgfgdfShaikh Muhammad Bin Zayed Al Nahyan Institute Of CardiologyTesting M')]</value>
      <webElementGuid>092cd32f-6855-470b-808c-907bc18f520b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
