<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_MR No_Send</name>
   <tag></tag>
   <elementGuidId>7ea879d6-4e63-444a-96da-32503e4e00f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Send</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Send']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2f600be4-806e-44ed-a966-c51638910156</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3d0bcc82-7d74-4017-8e36-d21d52d854e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Send</value>
      <webElementGuid>4741886d-228e-4d72-94a6-bbed73e133dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>61590f26-3a9e-4c17-903f-1b4dc60b8ae0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>CheckMRNo();</value>
      <webElementGuid>1c3bdfe5-bc30-4db2-8c0f-f009815bc5c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>8535ae2c-fcdb-4a53-9cf5-caa3f91afcb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Send&quot;)</value>
      <webElementGuid>79b517c0-9e10-466a-a10c-3b55246861b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Send']</value>
      <webElementGuid>2cdc7959-355a-4879-9e7d-3e9db79c68a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AddDivId']/div[2]/div/div/div/div/div[3]/input</value>
      <webElementGuid>e08910f6-5900-416c-a7ac-527f2a166d4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[3]/input</value>
      <webElementGuid>4accbfb0-ec44-4f0f-bbca-249f023fef72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'Send']</value>
      <webElementGuid>e03790b3-b20f-41c5-b5db-39ee8eaef9b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
