<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__SubmitRequestReceptionCashTransfer</name>
   <tag></tag>
   <elementGuidId>87dcef05-e8d1-4432-b50f-f5bd78ee2aae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='SubmitRequestReceptionCashTransfer']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#SubmitRequestReceptionCashTransfer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>93ad3dbd-73f2-49ae-b6bc-1f53cf2db054</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0f952158-d32f-4ea8-a2b0-04724b86a50e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SubmitRequestReceptionCashTransfer</value>
      <webElementGuid>9052e441-9da1-4b98-8cb6-47201795126d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>SaveForm()</value>
      <webElementGuid>1627f0b2-2975-4228-b014-70e0b8322818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>9ccbc998-2682-4d68-8085-f39a6baa93f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>79363ba0-f2e8-48d4-a5a8-6ddfb015a4ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SubmitRequestReceptionCashTransfer&quot;)</value>
      <webElementGuid>9b82f466-0757-431b-907a-3d5798eede5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='SubmitRequestReceptionCashTransfer']</value>
      <webElementGuid>ed77d2be-9838-4d18-a6be-4280b39bcf1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hideform']/input</value>
      <webElementGuid>9d9cfea6-79ab-424f-8488-4532df308a45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/div/input</value>
      <webElementGuid>3915abef-c48a-4036-824c-c249cb2f0705</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'SubmitRequestReceptionCashTransfer']</value>
      <webElementGuid>b408e509-b464-438c-a19f-9410ea6785ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
