<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search</name>
   <tag></tag>
   <elementGuidId>e5a9be55-9e6b-4489-89cf-6bb25ad77b4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@id='Search'])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DependentDisplayOnPanel > div.row > div.col-md-6.mb-2.row > div.col-md-2 > #Search</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>04cdb965-1088-471f-80ac-9e3b578cc6e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>bdd6e0d6-7704-4d3a-bd73-6378ba7cd7b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>45e2621d-2212-409d-9243-782c383a04e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>82fb724e-20a3-47d2-bc91-c47f2f292511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default pull-right</value>
      <webElementGuid>179a4703-79f7-4f4c-b3ed-ff3689006f1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>CheckCNICOnPanel()</value>
      <webElementGuid>79574baf-80fe-4744-b0af-e4cdcc5ce6b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>9f77c9b6-22a0-45ef-b12e-69240cc092ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EditPatientRegistrationFormForArmedForces&quot;)/div[@id=&quot;UserEducationDatatableDiv&quot;]/div[@class=&quot;kt-portlet__body&quot;]/div[@id=&quot;DependentDisplayOnPanel&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6 mb-2 row&quot;]/div[@class=&quot;col-md-2&quot;]/button[@id=&quot;Search&quot;]</value>
      <webElementGuid>eedcd83c-dad9-44f1-bc21-37a60df3da97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@id='Search'])[4]</value>
      <webElementGuid>f06d4757-064d-4ce7-a979-99d7f8cc8686</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DependentDisplayOnPanel']/div/div/div[3]/button</value>
      <webElementGuid>2b854c99-2206-4ae2-a280-69bf09aa7231</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please Enter Employee CNIC No'])[3]/following::button[1]</value>
      <webElementGuid>1afb8f50-644c-4fed-89c9-29b7b3c05211</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[73]/following::button[1]</value>
      <webElementGuid>29eddd73-0d36-47d5-8cfc-324333047769</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expiry Date'])[7]/preceding::button[1]</value>
      <webElementGuid>ed4d239b-11a7-4a21-aab4-0b41f4acf63f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name:'])[5]/preceding::button[1]</value>
      <webElementGuid>08872d49-a3b6-4981-831e-a8a22a7918ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div[3]/button</value>
      <webElementGuid>7dbfdcdd-fcd7-40d0-a397-bc0f8cad8551</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'Search' and @type = 'button' and @name = 'Search' and (text() = 'Search' or . = 'Search')]</value>
      <webElementGuid>3b6c0ccb-cdec-4915-921a-5d18066b56f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
