<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Fractionated_glyphicon glyphicon-trash</name>
   <tag></tag>
   <elementGuidId>c742e3ba-de47-4222-8bb8-f56847091d39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.glyphicon.glyphicon-trash</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='BloodBagInventoryTable']/tbody/tr/td[10]/a[2]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>f345bd2f-408e-47e6-b0b2-952b3f443c3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>glyphicon glyphicon-trash</value>
      <webElementGuid>707e2545-8b7e-46b1-a0f4-76441451e0fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BloodBagInventoryTable&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;text-center&quot;]/a[@class=&quot;Action Delete btn btn-sm btn-clean btn-icon btn-icon-md&quot;]/i[@class=&quot;glyphicon glyphicon-trash&quot;]</value>
      <webElementGuid>1d3ee674-c59d-4ca4-b3e4-d0f14323f00b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='BloodBagInventoryTable']/tbody/tr/td[10]/a[2]/i</value>
      <webElementGuid>1839f202-a0f0-4f5b-bbe1-67bc7557157c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/i</value>
      <webElementGuid>9da98409-518a-444a-8585-b6e92a83753e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
