<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__IssuancePatientIdentityNo</name>
   <tag></tag>
   <elementGuidId>1799dbc5-47ac-453d-8b83-6f2b5c895c3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#IssuancePatientIdentityNo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='IssuancePatientIdentityNo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>73a61a20-b221-41f4-904d-2bd6a95449ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>IssuancePatientIdentityNo</value>
      <webElementGuid>240de0bd-f1e4-4f25-bfe5-e5cc5cdbb958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IssuancePatientIdentityNo</value>
      <webElementGuid>61fd75d7-4b91-4405-8f85-fa1007060b3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>97a29f8c-7335-4f07-89e6-02423ad4e931</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c7fc34f0-eaeb-4671-9401-6e7072478100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>02682cc9-e53c-40f0-a3c5-dc0a2835e9e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Patient Identity </value>
      <webElementGuid>a08b8be4-b792-4568-b8d0-982ab18dc9f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>Utilities.TakeOnlyNormalValidInput(this)</value>
      <webElementGuid>133bd349-10c2-47e5-a59b-13bd712d6cfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>GetIssuancePatientDetails()</value>
      <webElementGuid>44fb60c8-d4a5-4950-83e0-40afdef7ee8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IssuancePatientIdentityNo&quot;)</value>
      <webElementGuid>8e7d50ed-730a-4c24-8481-439031263785</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='IssuancePatientIdentityNo']</value>
      <webElementGuid>dd93cb40-7152-4fe7-9d8f-2c5ad45efbc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='BloodBagIssuanceForm']/div/div/div[2]/div/div[2]/input</value>
      <webElementGuid>32421a38-fa7a-4dd6-8205-76dd4ac6480c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div[2]/div/div[2]/input</value>
      <webElementGuid>e74c5677-cc49-439a-964c-2c42c1ba9b81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'IssuancePatientIdentityNo' and @name = 'IssuancePatientIdentityNo' and @type = 'text' and @placeholder = 'Patient Identity ']</value>
      <webElementGuid>6216ff50-1b7f-4e3f-bfba-72e6835f4a37</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
