<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Remarks_UpdateSubmitId</name>
   <tag></tag>
   <elementGuidId>d223ac30-6c23-401b-9105-3ff6e659c0a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UpdateSubmitId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UpdateSubmitId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8f022ae1-264e-48da-9bd3-35e996366b98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8de8e7d7-44dd-40d8-9691-6694686d60a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UpdateSubmitId</value>
      <webElementGuid>6e674d4c-f491-442f-8899-075d363c1bf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>478b5de9-5ee2-46be-a80f-f1620df79c15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>9f47d6c4-f229-488f-a58b-91782ad83316</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UpdateSubmitId&quot;)</value>
      <webElementGuid>76eeb840-b127-499f-b6f9-acb04e6e7f01</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UpdateSubmitId']</value>
      <webElementGuid>0d06dd20-b58f-4043-bc59-7d8a75c1188b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hideform']/input</value>
      <webElementGuid>10ae3e53-a665-42c6-a078-2d6408f0a9a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>5932006b-74a2-48c6-a5d5-e9a431a337ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'UpdateSubmitId']</value>
      <webElementGuid>cf540e31-6d6b-44a4-ba3a-10c45460e0a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
