<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__PMDCNumber</name>
   <tag></tag>
   <elementGuidId>fc486606-6d42-4e57-8379-0dbf17dd17b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PMDCNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PMDCNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>977b9d06-2f69-4ecb-aee3-259abc4fcef3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PMDCNumber</value>
      <webElementGuid>a39a1598-b129-48aa-94d4-983055b72fe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1999ddf1-7b09-43ce-84f2-e81db922da71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PMDCNumber</value>
      <webElementGuid>475ccb6a-35ea-42ca-a88d-831557ac6adf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b47b3716-d258-4b01-b717-c325a21ddfad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>PMDC Number</value>
      <webElementGuid>72318015-7c27-4ce5-aa13-875d5dbe36dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>a97b8b96-2a58-40ea-96ba-7eca69da75d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bv-field</name>
      <type>Main</type>
      <value>PMDCNumber</value>
      <webElementGuid>bdf16ce9-3512-4b2f-ba1c-8ca24de6df1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PMDCNumber&quot;)</value>
      <webElementGuid>52689e02-3fc1-4c69-a690-9c09a5bf8cca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PMDCNumber']</value>
      <webElementGuid>e805c2a1-b9aa-45f1-beeb-ac5d9006d056</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pmdcDiv']/div/div/div[2]/input</value>
      <webElementGuid>e237f7ca-25c6-476d-aea5-057f96e93b40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div[2]/input</value>
      <webElementGuid>fca35edc-9f55-4792-be7d-579337a37884</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PMDCNumber' and @type = 'text' and @name = 'PMDCNumber' and @placeholder = 'PMDC Number']</value>
      <webElementGuid>06746428-aecc-4736-8d8b-32b29bd57a1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
