<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Mar 29, 2023 1531_glyphicon glyphicon-edit</name>
   <tag></tag>
   <elementGuidId>814a48db-5e60-41ea-abf6-88ed4ff3974a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.glyphicon.glyphicon-edit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='AccountCategoryTable']/tbody/tr/td[7]/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>e59f8f81-d23e-4621-a93f-28d6925e18c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>glyphicon glyphicon-edit</value>
      <webElementGuid>92717348-f50f-491d-9006-7cdd595b03cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccountCategoryTable&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;text-center&quot;]/a[@class=&quot;Action Update btn btn-sm btn-clean btn-icon btn-icon-md&quot;]/i[@class=&quot;glyphicon glyphicon-edit&quot;]</value>
      <webElementGuid>f57ee166-14cc-484e-9f94-7efd8dd23f80</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='AccountCategoryTable']/tbody/tr/td[7]/a/i</value>
      <webElementGuid>4316821f-83a9-4448-a19e-3375360e622a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/a/i</value>
      <webElementGuid>fdda2208-a844-48b6-a92d-3d64861e8293</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
