<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__DurationMax</name>
   <tag></tag>
   <elementGuidId>5de792ac-17d6-408c-922b-a0e49e3ffbb0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DurationMax']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DurationMax</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>909a61d3-b04e-4740-aeb6-56be871ba145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DurationMax</value>
      <webElementGuid>ce444446-4bc1-46ad-b615-74f3adbecf71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DurationMax</value>
      <webElementGuid>32384505-042c-4410-be65-603704478efa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>be3b5c4a-6182-419e-a5aa-d102843d4112</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4ae0dad3-4222-472c-8e62-1f8a87226c20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Max Duration</value>
      <webElementGuid>b4d90c1a-18f4-4e10-9e7c-c07d6cb2e918</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bv-field</name>
      <type>Main</type>
      <value>DurationMax</value>
      <webElementGuid>27443c88-f21a-417f-bbb4-c709eb4df532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DurationMax&quot;)</value>
      <webElementGuid>7c4cf370-568b-4059-a000-55f20f856eb3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DurationMax']</value>
      <webElementGuid>09308e07-3f22-4c26-be6d-d11039990633</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formMedicineDosages']/div/div[9]/div/div[2]/input</value>
      <webElementGuid>05bfea37-4ab6-4218-a0bb-b72fefd23944</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div[2]/input</value>
      <webElementGuid>a3d8129b-cd4e-42d8-97bc-3ca494cdc8bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'DurationMax' and @name = 'DurationMax' and @type = 'number' and @placeholder = 'Enter Max Duration']</value>
      <webElementGuid>6499b84a-50e3-4ff2-ba5f-40982d8c0888</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
