<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Description_BloodBankInstituteDescription</name>
   <tag></tag>
   <elementGuidId>d25d48a6-c172-4d3b-b0c1-d44f7f826831</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BloodBankInstituteDescription</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='BloodBankInstituteDescription']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>4e22858d-05e5-4a4d-8c77-8f99b90dee3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>8e6b1db6-eb1d-48ce-8bd1-c2290d288c08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>fe66edc7-809e-4e7b-b9e2-f2629803e76d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BloodBankInstituteDescription</value>
      <webElementGuid>63912b05-5fff-4d5b-b331-73b72da4def5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BloodBankInstituteDescription</value>
      <webElementGuid>4eeab866-f955-480a-b3a7-77e3ebe719f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>Utilities.TakeOnlyNormalValidInput(this)</value>
      <webElementGuid>48b9921b-5608-45a6-b9d4-10de68f8cc1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BloodBankInstituteDescription&quot;)</value>
      <webElementGuid>8e56fe41-6bc5-4f67-b0eb-400574e1ed57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='BloodBankInstituteDescription']</value>
      <webElementGuid>dccfa460-f34b-4ca9-a926-0a45e76fcd34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='BloodInstituteForm']/div/div[2]/div[7]/div/div/div[2]/textarea</value>
      <webElementGuid>2e1bdc1b-6f15-423c-8088-dce3a3b53560</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>af959264-1660-4b24-b6ae-2a9949bac90d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'BloodBankInstituteDescription' and @name = 'BloodBankInstituteDescription']</value>
      <webElementGuid>976a0dd0-9502-47e3-a166-01abb9ab9f68</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
