<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Submit</name>
   <tag></tag>
   <elementGuidId>98e8768a-b3bf-4962-a671-09ba0d0dad09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SharedButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='SharedButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fd5ae3b5-39f3-43ce-93ac-92fb8c32afb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SharedButton</value>
      <webElementGuid>cb0fd80e-ecdd-45b2-8e95-325fa0282c37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b4ccc6d7-6e56-49f7-8002-f2f58faa0a7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>7332d59a-4a23-4f10-9cf0-8c24339c6251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>cb71d65d-9ac4-4746-bdb6-2880a38678c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>13b01d77-b89e-46d9-9937-4270569aa8d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SharedButton&quot;)</value>
      <webElementGuid>0bdcbf1c-8a08-4a75-8b23-857fbdb9f82e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='SharedButton']</value>
      <webElementGuid>bacf459a-5217-4246-b9b0-ebebcc172f44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='PanelPackageDisposableForm']/div/div/div/div[13]/div/button</value>
      <webElementGuid>c92be898-74b1-465a-a2ba-f6344d7ba728</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please enter a valid value'])[8]/following::button[1]</value>
      <webElementGuid>970274d7-4bae-41b2-9b30-7b024e5d160d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Discount Will Be In Numbers'])[8]/following::button[1]</value>
      <webElementGuid>1a49500d-c92b-4358-b41c-c054a6114256</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::button[1]</value>
      <webElementGuid>29c87a0d-e24a-4d66-9e59-7d27fdac495a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Panel/Entitle Packages Disposables'])[1]/preceding::button[2]</value>
      <webElementGuid>a4a1e172-448d-435b-8653-e2058cc532a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Submit']/parent::*</value>
      <webElementGuid>281a3df2-8950-4ccd-ab50-4206830bed87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/button</value>
      <webElementGuid>365f716a-1a9f-4c65-9a8a-65602406596e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'SharedButton' and @type = 'button' and @name = 'Submit' and (text() = 'Submit' or . = 'Submit')]</value>
      <webElementGuid>684b90a9-b701-4874-8349-deb12081f887</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
