<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ul_Please Select StoreAcademic Affair Store_d5a44b</name>
   <tag></tag>
   <elementGuidId>642e557f-f060-40d5-a67b-8bcb75f3cce0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='select2-ListPharmacyStore-results']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-ListPharmacyStore-results</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
      <webElementGuid>12b1d1fd-252d-4c87-bd84-b8196fd44018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__options</value>
      <webElementGuid>2ebe2e78-e8ca-4278-8685-8512059701da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>d64f319c-4d12-4dab-af1b-6a350122ecb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-ListPharmacyStore-results</value>
      <webElementGuid>534f5f4b-c1e0-4aaf-a89f-f3399fca70aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>99cdadab-7ca8-4cd9-8cae-52657d62a492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b596cf7e-579d-46ae-8c5e-83e6c38dda13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please Select StoreAcademic Affair StoreAccounts StoreAdmin &amp; Security StoreAdmin StoreBait ul Maal StoreBio Gases StoreBiomedical StoreCash Store (Accounts)Cath Lab StoreCath Lab Store MPCCTV StoreCCU-1 StoreConference StoreCook StoreCoronary Care Unit-2 StoreCSSD StoreCT-Angio StoreDay Care StoreDDC StoreDental StoreDMS Admin StoreDoctor Hostel StoreECG StoreEcho StoreED Office StoreED OPD StoreElectric StoreEmergency Medicine StoreEmergency MP StoreEP StoreERC StoreETT StoreExchange StoreFiltration Plant StoreFinance StoreGardener StoreGeneral StoreGeneral Ward StoreGenerator StoreGynae Ward StoreHDU-2 StoreHostel StoreHvac StoreIncinerator StoreIntensive Care Unit Store (ITC)IPD PharmacyIT Department StoreITC III StoreLaboratory StoreLaundryLibrary StoreLift storeLP StoreMain Disposable StoreMain Laboratory StoreMain Stock &amp; Accessories StoreMain Store Cath LabMatron StoreMedicine StoreModel Pharmacy Main StoreModel Pharmacy StoreModelPharmacyMP Cardiac Medicine StoreMP ITC/ICU StoreMRIMS Office StoreMSDS StoreNeurology StoreNuclear Medicine StoreNursing Hostel StoreOPD PharmacyOPD Reception StoreOPD StoreOT Anesthesia StoreOT Medicine and Disposible StoreOT Perfusion StoreOT Store GeneralOT Store MedicineOT Store MPOT Surgery StoreP &amp; D StorePaeds Ward StorePainter StorePhysiotherapy StorePlumber StorePost Cath 1 &amp; 2 StorePreload StorePrimary PCI StorePrivatePrivate Surgical Ward StorePsychology StorePurchase StoreRadiology MP StoreRadiology StoreRecord Room StoreRepeat Medicine StoreSatellite Pharmacy Cath LabSatellite Pharmacy ERSatellite Pharmacy OTSpecial Private Ward StoreSSP  StoreSurgical Ward StoreTac storetailor StoreTechnical StoreTransport StoreTube Well StoreVIP Storewqertyj</value>
      <webElementGuid>24ce0f02-ce2d-476d-9259-67905b6d8e96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-ListPharmacyStore-results&quot;)</value>
      <webElementGuid>ee3f2d24-8511-4ddd-aeb6-ec6a0dc63c4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//ul[@id='select2-ListPharmacyStore-results']</value>
      <webElementGuid>1b1be84b-fa26-41a8-ac9c-c04e5c0f48cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='There are no User Available for this Store'])[1]/following::ul[1]</value>
      <webElementGuid>22764dc3-74f7-4691-b1b4-1b12f24075b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'select2-ListPharmacyStore-results', '&quot;', ')')])[1]/following::ul[1]</value>
      <webElementGuid>5c024e45-47df-4af9-b367-3935541e2f1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/ul</value>
      <webElementGuid>c5f2b2b1-fa4b-4fe4-9738-281f7f5f94ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ul[@id = 'select2-ListPharmacyStore-results' and (text() = 'Please Select StoreAcademic Affair StoreAccounts StoreAdmin &amp; Security StoreAdmin StoreBait ul Maal StoreBio Gases StoreBiomedical StoreCash Store (Accounts)Cath Lab StoreCath Lab Store MPCCTV StoreCCU-1 StoreConference StoreCook StoreCoronary Care Unit-2 StoreCSSD StoreCT-Angio StoreDay Care StoreDDC StoreDental StoreDMS Admin StoreDoctor Hostel StoreECG StoreEcho StoreED Office StoreED OPD StoreElectric StoreEmergency Medicine StoreEmergency MP StoreEP StoreERC StoreETT StoreExchange StoreFiltration Plant StoreFinance StoreGardener StoreGeneral StoreGeneral Ward StoreGenerator StoreGynae Ward StoreHDU-2 StoreHostel StoreHvac StoreIncinerator StoreIntensive Care Unit Store (ITC)IPD PharmacyIT Department StoreITC III StoreLaboratory StoreLaundryLibrary StoreLift storeLP StoreMain Disposable StoreMain Laboratory StoreMain Stock &amp; Accessories StoreMain Store Cath LabMatron StoreMedicine StoreModel Pharmacy Main StoreModel Pharmacy StoreModelPharmacyMP Cardiac Medicine StoreMP ITC/ICU StoreMRIMS Office StoreMSDS StoreNeurology StoreNuclear Medicine StoreNursing Hostel StoreOPD PharmacyOPD Reception StoreOPD StoreOT Anesthesia StoreOT Medicine and Disposible StoreOT Perfusion StoreOT Store GeneralOT Store MedicineOT Store MPOT Surgery StoreP &amp; D StorePaeds Ward StorePainter StorePhysiotherapy StorePlumber StorePost Cath 1 &amp; 2 StorePreload StorePrimary PCI StorePrivatePrivate Surgical Ward StorePsychology StorePurchase StoreRadiology MP StoreRadiology StoreRecord Room StoreRepeat Medicine StoreSatellite Pharmacy Cath LabSatellite Pharmacy ERSatellite Pharmacy OTSpecial Private Ward StoreSSP  StoreSurgical Ward StoreTac storetailor StoreTechnical StoreTransport StoreTube Well StoreVIP Storewqertyj' or . = 'Please Select StoreAcademic Affair StoreAccounts StoreAdmin &amp; Security StoreAdmin StoreBait ul Maal StoreBio Gases StoreBiomedical StoreCash Store (Accounts)Cath Lab StoreCath Lab Store MPCCTV StoreCCU-1 StoreConference StoreCook StoreCoronary Care Unit-2 StoreCSSD StoreCT-Angio StoreDay Care StoreDDC StoreDental StoreDMS Admin StoreDoctor Hostel StoreECG StoreEcho StoreED Office StoreED OPD StoreElectric StoreEmergency Medicine StoreEmergency MP StoreEP StoreERC StoreETT StoreExchange StoreFiltration Plant StoreFinance StoreGardener StoreGeneral StoreGeneral Ward StoreGenerator StoreGynae Ward StoreHDU-2 StoreHostel StoreHvac StoreIncinerator StoreIntensive Care Unit Store (ITC)IPD PharmacyIT Department StoreITC III StoreLaboratory StoreLaundryLibrary StoreLift storeLP StoreMain Disposable StoreMain Laboratory StoreMain Stock &amp; Accessories StoreMain Store Cath LabMatron StoreMedicine StoreModel Pharmacy Main StoreModel Pharmacy StoreModelPharmacyMP Cardiac Medicine StoreMP ITC/ICU StoreMRIMS Office StoreMSDS StoreNeurology StoreNuclear Medicine StoreNursing Hostel StoreOPD PharmacyOPD Reception StoreOPD StoreOT Anesthesia StoreOT Medicine and Disposible StoreOT Perfusion StoreOT Store GeneralOT Store MedicineOT Store MPOT Surgery StoreP &amp; D StorePaeds Ward StorePainter StorePhysiotherapy StorePlumber StorePost Cath 1 &amp; 2 StorePreload StorePrimary PCI StorePrivatePrivate Surgical Ward StorePsychology StorePurchase StoreRadiology MP StoreRadiology StoreRecord Room StoreRepeat Medicine StoreSatellite Pharmacy Cath LabSatellite Pharmacy ERSatellite Pharmacy OTSpecial Private Ward StoreSSP  StoreSurgical Ward StoreTac storetailor StoreTechnical StoreTransport StoreTube Well StoreVIP Storewqertyj')]</value>
      <webElementGuid>4d40ac0c-796b-47b6-a947-6a6998ddc0fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
