<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Opening Balance Remarks_OpeningBal_d1ba1f</name>
   <tag></tag>
   <elementGuidId>82ce863b-99eb-40ce-b470-996a2dd6f948</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='OpeningBalanceRemarks']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#OpeningBalanceRemarks</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>6b05b4f6-15f5-4817-8ae6-1e40ddd9ca83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7a14db4a-9b2f-465d-8e70-4463de0b1b67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ae10e68e-1a18-4359-b5e3-ae3927c52a40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>OpeningBalanceRemarks</value>
      <webElementGuid>892fce01-7c29-4325-894f-75477b499f78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>OpeningBalanceRemarks</value>
      <webElementGuid>277f9440-bba3-4936-84d9-cd9f72c3ab0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Opening Balance Remarks</value>
      <webElementGuid>58c0f1af-0128-4a8a-8d0c-bab2b16615ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a71eab50-3560-48b6-917f-60794c3c90b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OpeningBalanceRemarks&quot;)</value>
      <webElementGuid>43159650-1e3c-4170-ad02-e9fe709052ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='OpeningBalanceRemarks']</value>
      <webElementGuid>87945803-e7a4-4e25-b615-540f5fe7baa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='ReceptionCashOpeningForm']/div/div/div[2]/div[2]/textarea</value>
      <webElementGuid>dd4d7787-4175-46d1-8ff5-69233cc171ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>1767799f-da38-4894-a01d-53a6f1c13743</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@type = 'text' and @id = 'OpeningBalanceRemarks' and @name = 'OpeningBalanceRemarks' and @placeholder = 'Enter Opening Balance Remarks']</value>
      <webElementGuid>5911600b-ada3-40bc-98d3-016112d894bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
