<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sign In</name>
   <tag></tag>
   <elementGuidId>fc5e646c-dac0-4d48-8e9e-89e92529d35d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#kt_login_signin_submit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='kt_login_signin_submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d48c1f09-af36-4af2-9063-5abd88707c85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>kt_login_signin_submit</value>
      <webElementGuid>ea60214e-fc3c-4fd4-8fe9-dcd281cf8cb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>kt_login_signin_submit</value>
      <webElementGuid>69e81b48-919e-4881-a713-1b1c6ca73b59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>login</value>
      <webElementGuid>1fc2d232-f13f-41f3-b6c5-43db7d9ca2dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-elevate kt-login__btn-primary</value>
      <webElementGuid>44d6a11f-cd88-4170-8a18-33a824d7bc64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign In</value>
      <webElementGuid>ef400086-eadb-4ad0-992b-5ae0f5e965b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_login_signin_submit&quot;)</value>
      <webElementGuid>91e3430c-4163-4a75-8ad6-cf98c502c15c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='kt_login_signin_submit']</value>
      <webElementGuid>23876a08-559f-4355-8112-ee01fa90b856</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='kt_login_form']/div[3]/button</value>
      <webElementGuid>4af928b3-948c-4f73-bf05-4c9c1d8e527f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot Password ?'])[1]/following::button[1]</value>
      <webElementGuid>cd3f51a8-d761-45f9-ba7a-a3ccc0d5396f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign In'])[1]/following::button[1]</value>
      <webElementGuid>b4e58227-006e-40cc-908a-798473a1e6d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'kt_login_signin_submit', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>e507abd5-b26e-466e-8c99-b79bedaa398a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>0008cc9a-4042-4b5c-b955-026770a06518</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'kt_login_signin_submit' and @name = 'kt_login_signin_submit' and (text() = 'Sign In' or . = 'Sign In')]</value>
      <webElementGuid>b6d9c93d-e41d-488a-8a50-e3a43080c604</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
