<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Services</name>
   <tag></tag>
   <elementGuidId>20cb0a33-71a1-40f2-8401-a203f85577fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='SubserviceDiv']/div[4]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.form-group.row.conFeeS.has-feedback > div.col-md-4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>da4d8325-616f-4f29-8e3a-0d1daa14a9ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md-4</value>
      <webElementGuid>cb15b84d-9eae-46ea-b13b-f3ccfc65952b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    Services:*
                                </value>
      <webElementGuid>e5de1e86-c950-4b2d-a0aa-397f802e24dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SubserviceDiv&quot;)/div[@class=&quot;form-group row conFeeS has-feedback&quot;]/div[@class=&quot;col-md-4&quot;]</value>
      <webElementGuid>9ac30654-2664-4383-9461-f856163719c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SubserviceDiv']/div[4]/div</value>
      <webElementGuid>ddbc32e4-1253-4167-98cf-ae1019be5cb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Department First'])[2]/following::div[2]</value>
      <webElementGuid>12c96368-3f7c-4dd1-a644-eae90b5f6d9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deselect All'])[2]/following::div[3]</value>
      <webElementGuid>0bf3cec8-7057-4e18-ab62-a6432da6234c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[4]/div</value>
      <webElementGuid>0b9b39b9-b132-4174-81e9-e7ab86325fc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
                                    Services:*
                                ' or . = '
                                    Services:*
                                ')]</value>
      <webElementGuid>5a7b59b2-438b-4007-bf4b-0e62592325ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
