<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Coronary Care Unit-2</name>
   <tag></tag>
   <elementGuidId>a4bd42d2-140c-459c-a61d-f290d989d282</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='bs-select-5-1']/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bs-select-5-1 > span.text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7dd2011a-bd31-4482-8329-69b922433be1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0ef3ebf2-d3b3-41e0-b0fa-0b37896ece17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Coronary Care Unit-2</value>
      <webElementGuid>64526564-ae3b-40b4-90b2-f270946dd300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bs-select-5-1&quot;)/span[@class=&quot;text&quot;]</value>
      <webElementGuid>a852abdd-ce80-4079-88dd-8d965fb84ff5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='bs-select-5-1']/span[2]</value>
      <webElementGuid>ded0afd9-86e4-4699-b7a9-ed374877af3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admissions'])[1]/following::span[2]</value>
      <webElementGuid>f3e1f091-082d-4e33-b6de-6125dafaf49f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deselect All'])[3]/following::span[3]</value>
      <webElementGuid>e0882bd2-8cfa-478b-b73e-85af34c59709</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Post Cath Ward'])[5]/preceding::span[2]</value>
      <webElementGuid>eaf349c5-d6d5-43e4-a382-94758faa7d82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Special Private Ward'])[5]/preceding::span[4]</value>
      <webElementGuid>c992110c-4354-4e48-8ffc-e29b046f6239</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/div[3]/ul/li[2]/a/span[2]</value>
      <webElementGuid>13c948fd-9d7e-411f-b0a4-e20d0dafc1f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Coronary Care Unit-2' or . = 'Coronary Care Unit-2')]</value>
      <webElementGuid>b1f21c53-be17-41e1-86e8-f371ae4b6311</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
