<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__PayeeCellsRowPaddingTop</name>
   <tag></tag>
   <elementGuidId>980392f2-7c67-405e-a56c-a69e5d4513ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PayeeCellsRowPaddingTop</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PayeeCellsRowPaddingTop']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ace0b013-eb69-44eb-bdbe-c67617ee13a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>ecfc0308-31b8-4943-983c-2528d720b1ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PayeeCellsRowPaddingTop</value>
      <webElementGuid>529e8164-1942-4569-8852-6d2610228ab8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>any</value>
      <webElementGuid>b984aad5-1d5e-487b-8b63-2854ac99a9d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PayeeCellsRowPaddingTop</value>
      <webElementGuid>fc974cc0-4db2-4a48-be37-53cef50d0a6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>Utilities.TakeOnlyNormalValidInput(this)</value>
      <webElementGuid>422b51bb-54ae-4ba2-82c0-091e880dbff1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>ee768092-6342-4852-824a-8e8caa2169d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>00fcdcf0-8526-4d40-ac2a-0d5903460c2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Payee Cells Row Padding Top</value>
      <webElementGuid>11e6bc4f-071c-481a-89b3-406c13afb6b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bv-field</name>
      <type>Main</type>
      <value>PayeeCellsRowPaddingTop</value>
      <webElementGuid>b2402a8e-0167-45db-878f-63b2fa37e688</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PayeeCellsRowPaddingTop&quot;)</value>
      <webElementGuid>cafa5789-15b0-40e3-aa9d-da4d08731aa6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PayeeCellsRowPaddingTop']</value>
      <webElementGuid>a148fb7e-6fcd-44ea-b9a8-7e204d9dd2d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myDIV']/div/div[4]/div[2]/div/div[2]/input</value>
      <webElementGuid>2a75295e-3b39-408f-b682-1c35582ca394</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div[2]/input</value>
      <webElementGuid>10b7ec2a-0820-4799-9f96-90b03de66c36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'PayeeCellsRowPaddingTop' and @name = 'PayeeCellsRowPaddingTop' and @placeholder = 'Payee Cells Row Padding Top']</value>
      <webElementGuid>989735a1-3ad5-4319-a030-d1a78740c9a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
