<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Please enter a value with valid lengt_18a3d1</name>
   <tag></tag>
   <elementGuidId>fce14cf3-649b-42eb-add0-d827022a4efe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UpdateSubmitId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UpdateSubmitId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9bccaa99-a95f-4f37-8a10-37b446874765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>53930e40-286a-4d4a-9fc8-d2e4145ba618</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UpdateSubmitId</value>
      <webElementGuid>d0f9fb79-f8df-4d91-82a6-14b3626a20e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>ca4b0316-dcfb-49be-9c9c-16d71ca383a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>92370fd5-89be-4901-80c9-bc158b6b2939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UpdateSubmitId&quot;)</value>
      <webElementGuid>4a7195c9-e5aa-4faa-9d7a-d53d74192e1f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UpdateSubmitId']</value>
      <webElementGuid>e79d4ee5-9ecd-48ae-94be-c72ea234d3c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='hideform']/input)[2]</value>
      <webElementGuid>25f22723-2720-41ab-85ff-b66e141f3096</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[6]/div/input</value>
      <webElementGuid>1603b76e-0801-4aa2-a8e0-e2d48019977b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'UpdateSubmitId']</value>
      <webElementGuid>dbcc156e-c3c4-44ef-a5b6-5ce2b0eef171</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
