<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__splittingIndex</name>
   <tag></tag>
   <elementGuidId>4e608de3-8090-4621-906b-ff3d52420af8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#splittingIndex</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='splittingIndex']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d7f85d55-cf0a-4532-8171-6eda79c80d41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>005e7067-3bf5-426b-bc44-5409022d9cd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>splittingIndex</value>
      <webElementGuid>3d1412f0-d500-4c5e-88ca-0d541f8e2b4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>splittingIndex</value>
      <webElementGuid>7e45ac15-d22b-434a-a76e-650767528a79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>Utilities.TakeOnlyInputNumbers(event)</value>
      <webElementGuid>78619b34-e759-4949-a932-7096e21f2f2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>b136053c-9017-4d3f-8d97-6c136b259fc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>bb2e0e1f-f47e-4add-8f55-0e2be0282424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Splitting Index</value>
      <webElementGuid>5f02b14d-4c60-4d0f-bc73-fd48e60f2e25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bv-field</name>
      <type>Main</type>
      <value>splittingIndex</value>
      <webElementGuid>0c645285-f556-4e85-93ae-8cadf03e659d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;splittingIndex&quot;)</value>
      <webElementGuid>be7ba445-d732-44db-bde2-30d290572173</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='splittingIndex']</value>
      <webElementGuid>582986f7-ebb7-48cc-b4ce-bf50404cbd8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myDIV']/div/div[3]/div[2]/div/div[2]/input</value>
      <webElementGuid>48b149fb-4475-4236-98d9-5d8d1460ad29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div[2]/input</value>
      <webElementGuid>b08542d0-e47c-4511-909b-83829acf958d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'splittingIndex' and @name = 'splittingIndex' and @placeholder = 'Splitting Index']</value>
      <webElementGuid>2bd32bab-e575-4437-a8ae-71d17b0c8478</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
