<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__TransactionDate</name>
   <tag></tag>
   <elementGuidId>457f9134-e3e5-4842-aaf2-e6d5bb937d09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TransactionDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TransactionDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e2b6e968-024d-4f36-b1ed-a44d773c9c8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TransactionDate</value>
      <webElementGuid>6ef3220b-1d28-493a-a4ea-c8f976ab652f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TransactionDate</value>
      <webElementGuid>c8c4cd9f-675f-4afe-acc1-60078da47aae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1548d1d1-5092-481a-903e-4ca48c4769bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control datepicker TransactionDate</value>
      <webElementGuid>109f6522-6a1c-425e-8c75-a7ae41b6f2c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>DD/MM/YYYY</value>
      <webElementGuid>adc3d590-2798-4c87-a7b4-150778690685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bv-field</name>
      <type>Main</type>
      <value>TransactionDate</value>
      <webElementGuid>73345220-a688-4e3a-aa75-b8228614bba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TransactionDate&quot;)</value>
      <webElementGuid>b7ae39f0-b860-4e7c-a893-19b61a54e36d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TransactionDate']</value>
      <webElementGuid>de112ea2-5f9a-4730-b993-9567bb54aa2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myDIV']/div/div/div[2]/div[2]/input</value>
      <webElementGuid>62a0bca0-796f-4fa5-85a5-0e4e364d9714</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>48da85ce-8f34-4381-bf0e-c008b25a1bcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'TransactionDate' and @name = 'TransactionDate' and @type = 'text' and @placeholder = 'DD/MM/YYYY']</value>
      <webElementGuid>9f41e638-b1ac-457c-a53a-8d1633d6cb8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
