<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__StartDate</name>
   <tag></tag>
   <elementGuidId>dc8e1569-2607-41da-b847-b65af37a5e51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='StartDate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#StartDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6c099adc-dd6a-408c-876e-f2cd976a804e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>StartDate</value>
      <webElementGuid>3e7f9aa6-a4b8-400e-9b22-cfef9c1419c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>34b5b4a3-ac5c-419b-bbee-0795d23facfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>StartDate</value>
      <webElementGuid>046a86f2-7f83-45e1-8fbc-26fa20a1f219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>248ced51-ace2-4986-a93a-9e808d340896</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control </value>
      <webElementGuid>9f259b97-5e58-41b5-a4af-b42f125d9eb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Start Date</value>
      <webElementGuid>a9fd97d9-8209-4348-809d-a2924228d234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bv-field</name>
      <type>Main</type>
      <value>StartDate</value>
      <webElementGuid>ab3fb85b-7fbc-49e4-93b3-9cb90af8a6bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;StartDate&quot;)</value>
      <webElementGuid>a4158bae-2bd8-41dc-9670-abe31275d485</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='StartDate']</value>
      <webElementGuid>ae8cd499-8b22-4025-9f9e-8f44ae6125b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FinancialYearForm']/div[2]/div/div/div[2]/input</value>
      <webElementGuid>8aa54aa3-4c51-474d-babf-fe46e3380597</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/input</value>
      <webElementGuid>455c336c-7087-4563-b488-7d5abeb22f1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'StartDate' and @name = 'StartDate' and @type = 'text' and @placeholder = 'Start Date']</value>
      <webElementGuid>1384e24f-175c-4c9f-b777-aa18ea949529</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
