<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_CT.BT</name>
   <tag></tag>
   <elementGuidId>ee533677-19e4-4aef-affb-054d04cb279a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='bs-select-1-5']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bs-select-1-5 > span.text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5886874c-1bf3-445f-ad3d-85248120cc3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3281958e-6e79-4ada-a827-a80c37d643d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CT.BT</value>
      <webElementGuid>b5fce36e-ea88-4215-bba1-5d59f731f7a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bs-select-1-5&quot;)/span[@class=&quot;text&quot;]</value>
      <webElementGuid>0493354b-c84d-4160-a6ab-290b0cff05e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='bs-select-1-5']/span</value>
      <webElementGuid>7717a2fa-49f7-4c21-858a-d2bd0b0c1061</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MRI Leg Plain'])[2]/following::span[1]</value>
      <webElementGuid>b93876eb-02d0-4409-8cd1-9b13e127d46e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dressing / Temp filling'])[2]/following::span[2]</value>
      <webElementGuid>acb0fa49-1a68-43ce-bf64-174029e89a52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CK-MB'])[2]/preceding::span[1]</value>
      <webElementGuid>3d1ca1d1-b32b-48bf-af26-3376226f096f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CT-Abdomin + Pelvis'])[2]/preceding::span[2]</value>
      <webElementGuid>dad0a1c5-9489-4537-b333-66e8aa91b912</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[6]/a/span</value>
      <webElementGuid>9d0264ba-df17-4a1c-8dc1-fa22ed58051e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'CT.BT' or . = 'CT.BT')]</value>
      <webElementGuid>80edcba9-b280-49b2-b347-24947364425e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
