<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select</name>
   <tag></tag>
   <elementGuidId>fcdeb735-df16-4e44-95ce-d133b2ae73d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-NewMedicineName-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-NewMedicineName-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cd10df8a-8e31-471e-b8d1-9078a5d3af76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>1eb2186f-13ad-4344-8c05-b1f9daef487c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-NewMedicineName-container</value>
      <webElementGuid>7be936f0-b4b8-469d-a44d-29eb72b9bd84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>a7cce91f-2e31-49ec-8af6-82278ba65007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e16215e5-b988-4e43-a036-7c717db28831</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>d0859ce7-1d5e-4874-885e-4a8460b9042a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-NewMedicineName-container&quot;)</value>
      <webElementGuid>421e7bd3-63ec-4b33-ab03-877fe19c45db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-NewMedicineName-container']</value>
      <webElementGuid>4c6659a8-e3fa-41fe-9506-b76b25710197</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AddDivId']/div[2]/div/div/div/div/div[2]/span/span/span/span</value>
      <webElementGuid>6b5c530a-531b-4044-ab5f-2aab236f53c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::span[4]</value>
      <webElementGuid>9fbd9d7f-baed-476d-bd73-ad41567497b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please Select Item'])[1]/preceding::span[4]</value>
      <webElementGuid>8c6c34d1-8a86-4306-a895-5f10138f59bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/span/span/span/span</value>
      <webElementGuid>5df4600f-6ecb-4e53-a4ec-f2ee7114ed68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-NewMedicineName-container' and (text() = 'Select' or . = 'Select')]</value>
      <webElementGuid>04e3c2e6-a198-47db-937c-853f4d3453fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
