<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Cath Lab</name>
   <tag></tag>
   <elementGuidId>a3e8481d-d150-4623-b8cb-22a5e15c03e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SubDepartmentId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='SubDepartmentId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3e07acbc-1e9b-49b5-90fd-af7c9f7f673c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectpicker form-control hiddenField</value>
      <webElementGuid>312322c6-f3f6-4e1b-b9fd-a412493a09e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-actions-box</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>ccb26421-a496-45d7-b819-7d2c5ce9bdb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-live-search</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ac050a21-c19e-4b16-bcff-6b7ca549de8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SubDepartmentId</value>
      <webElementGuid>d09646f9-a0e9-49d3-b64b-2b599710336a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>multiple</name>
      <type>Main</type>
      <value>multiple</value>
      <webElementGuid>cec562b2-3774-41e7-a8be-86fc4665016e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SubDepartmentId</value>
      <webElementGuid>eff376dc-68af-442b-9675-6fc0327dc38b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-98</value>
      <webElementGuid>e8107534-f945-4526-8e71-7fa253c47dd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cath Lab</value>
      <webElementGuid>273f2900-c805-4ec1-8b3c-1eb5c69ea19b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SubDepartmentId&quot;)</value>
      <webElementGuid>9510c71a-339e-4bb8-9924-7ae58cb752d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='SubDepartmentId']</value>
      <webElementGuid>bc7684fd-a8e7-41da-9634-33e35b584620</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SubserviceDiv']/div[2]/div/div[2]/div/select</value>
      <webElementGuid>16cdcb9e-efaa-4e89-925a-c0a08d03a81c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sub Department(s)'])[1]/following::select[1]</value>
      <webElementGuid>698778f5-4ba7-40a6-bf01-01f2719e5647</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please Select Department'])[1]/following::select[1]</value>
      <webElementGuid>4e6d8caa-705f-4a37-81ff-57fb469f7234</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please Select'])[1]/preceding::select[1]</value>
      <webElementGuid>c4afcb0b-3532-4480-9410-27258bbe411a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select All'])[1]/preceding::select[1]</value>
      <webElementGuid>3bc6bab5-fd4a-4615-9b80-ac5b7cc8d585</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/select</value>
      <webElementGuid>cb802c1f-ead0-45d8-9601-94028664cb1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'SubDepartmentId' and @name = 'SubDepartmentId' and (text() = 'Cath Lab' or . = 'Cath Lab')]</value>
      <webElementGuid>ff5707ac-8f59-4724-9941-032dff5f6d74</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
