<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__CNICNumber</name>
   <tag></tag>
   <elementGuidId>fb161996-c56c-4138-9cfb-790426129085</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CNICNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CNICNumber</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>48b7d7b0-8a87-452d-93d4-a3d1f25c76a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CNICNumber</value>
      <webElementGuid>10733a43-f6c8-465d-a68b-596f9a776aec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0a202267-5229-4b04-84c0-fee0a665aa11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CNICNumber</value>
      <webElementGuid>9d8e3806-1609-422f-bd46-9b86a8cfe4bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control CNICIdentityInput</value>
      <webElementGuid>e9f04d77-93bc-4143-8297-045086f58ce5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>CNIC</value>
      <webElementGuid>fd676720-29fa-4978-9d51-a31aed3372be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bv-field</name>
      <type>Main</type>
      <value>CNICNumber</value>
      <webElementGuid>95c8c5f1-37d0-4262-b95c-692543e93939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>092cc540-e80b-4de3-8db2-7c1d0eed99af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CNICNumber&quot;)</value>
      <webElementGuid>1b9d4101-41ab-4b56-894f-e256b14d586f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CNICNumber']</value>
      <webElementGuid>79622fbb-89e7-41de-b04e-5f1b7e2de16a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CNICNumberDiv']/div[2]/input</value>
      <webElementGuid>fda0cf51-aafc-4ea9-9623-04927ba68c1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/input</value>
      <webElementGuid>aab1c87b-4711-4ae3-ac21-448a8e9161fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'CNICNumber' and @type = 'text' and @name = 'CNICNumber' and @placeholder = 'CNIC']</value>
      <webElementGuid>7191518a-ff61-4dc5-8b67-d4509a79204c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
