<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Jan 24, 2023 1156_EditInModal  btn btn-sm_c247c7</name>
   <tag></tag>
   <elementGuidId>4afd1fe7-4899-4de9-b4e5-7b32b54d425c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.EditInModal.btn.btn-sm.btn-clean.btn-icon.btn-icon-md</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='Patients']/tbody/tr/td[6]/a[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d38694ec-b0e7-429a-89c5-38e78d478c9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>cf985683-588e-4ee4-a33c-e017b9c0ff73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placement</name>
      <type>Main</type>
      <value>top</value>
      <webElementGuid>fbb83339-49ba-474b-a9d7-808ff3d89d0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>86c249af-27f0-4ceb-a595-e393974413b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>EditInModal  btn btn-sm btn-clean btn-icon btn-icon-md</value>
      <webElementGuid>c1814e8a-7d5f-4690-88fa-3dc49adb6258</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Patients&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;RowActions text-center&quot;]/a[@class=&quot;EditInModal  btn btn-sm btn-clean btn-icon btn-icon-md&quot;]</value>
      <webElementGuid>a81cf33e-59fa-4ccc-bb0c-4b39536ba796</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='Patients']/tbody/tr/td[6]/a[7]</value>
      <webElementGuid>580af060-0c90-4a19-b735-f97bf51cd6d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jan 24, 2023 11:56'])[1]/following::a[7]</value>
      <webElementGuid>177c6411-4ff1-4c08-ba75-87b3b64762ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Male'])[1]/following::a[7]</value>
      <webElementGuid>3fede1f4-4e62-45b8-8a54-065e70d8c4dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Male'])[2]/preceding::a[4]</value>
      <webElementGuid>1b45da1f-59fe-4b9a-8612-76ea3f781355</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/a[7]</value>
      <webElementGuid>fb12fa17-a1b4-4f01-988e-83ba17f0b3e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Edit']</value>
      <webElementGuid>6c0a2834-34cb-4d0f-9adb-406df4fc413b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
