<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__CovidTestValidity</name>
   <tag></tag>
   <elementGuidId>2d33f5f9-2625-490d-8ced-fcb238e07cb2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CovidTestValidity</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CovidTestValidity']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6f64fea3-eab8-430d-bf28-dae52f8243cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CovidTestValidity</value>
      <webElementGuid>58363dc0-74ea-44db-87af-40e48fde7937</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ce91bca0-16a9-4439-83ee-c7037410fe4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CovidTestValidity</value>
      <webElementGuid>b1f2e795-b8d2-4a16-9c7c-8b41e4e55501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6c2d2264-f52c-44e4-a5fc-c4c0644582f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>Utilities.TakeOnlyNormalValidInput(this)</value>
      <webElementGuid>4b2faf49-abd5-4090-9e74-0fc8bdf0ed9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>4a1ad1af-5ffc-464c-ac53-79e37002016c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Validity Hours</value>
      <webElementGuid>e2394338-4009-49da-ae67-a50d2a0f4cf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bv-field</name>
      <type>Main</type>
      <value>CovidTestValidity</value>
      <webElementGuid>352957c3-ceab-445f-9000-451d02de3f9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CovidTestValidity&quot;)</value>
      <webElementGuid>34d89644-668f-4027-ac66-f977c7dc18f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CovidTestValidity']</value>
      <webElementGuid>0015e744-632f-4f2f-9977-17dc5affcdc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myDIV']/div/div/div[3]/div[2]/div/input</value>
      <webElementGuid>86a2f95e-ecbc-48b4-9e9f-6aacde44a23a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/input</value>
      <webElementGuid>ed1b1bae-d86c-4589-9d37-9126a5cc38f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'CovidTestValidity' and @name = 'CovidTestValidity' and @type = 'text' and @placeholder = 'Validity Hours']</value>
      <webElementGuid>fc7cb145-220b-44f9-a224-8928d8e3e6a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
