<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ul_Searching-.asdfrGDgm</name>
   <tag></tag>
   <elementGuidId>43df4b9c-b32c-4f50-966e-6675769c8f13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-UnitId-results</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='select2-UnitId-results']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
      <webElementGuid>69c0c19a-8a58-4c4d-ac7e-e361842ae35c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__options</value>
      <webElementGuid>2a9b36a8-e785-4920-8621-fafff9dd384d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>4ebca997-d74f-499b-bfda-a5a07b66bdd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-UnitId-results</value>
      <webElementGuid>551df040-d85a-4371-b477-a11b09236d55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4867ea20-4bb0-48b8-8868-464024dfda4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>deb38f44-248b-4868-adbe-4123d2a208df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Searching…-%.asdfrGDgm</value>
      <webElementGuid>7af06cfe-5fb7-4762-a787-3481708c0646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-UnitId-results&quot;)</value>
      <webElementGuid>5a4668c7-b253-410f-97df-76b144c7bc22</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//ul[@id='select2-UnitId-results']</value>
      <webElementGuid>d6afbac8-c78b-4fc5-a6ae-55613a5b82ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'select2-UnitId-results', '&quot;', ')')])[1]/following::ul[1]</value>
      <webElementGuid>6a7ac320-0ea0-4dc0-afa7-169b6195ff73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Set Waiting Time'])[1]/following::ul[1]</value>
      <webElementGuid>57fd9475-12a0-469e-84ae-618f69e16230</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/ul</value>
      <webElementGuid>575a601d-6f1c-4c47-a21b-2d6d21a9af10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ul[@id = 'select2-UnitId-results' and (text() = 'Searching…-%.asdfrGDgm' or . = 'Searching…-%.asdfrGDgm')]</value>
      <webElementGuid>8d02e7fb-0ad4-4cc4-940e-9bdbaed6f65a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
