<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(0 - 25) UL_numeric0</name>
   <tag></tag>
   <elementGuidId>61a96a73-4ffb-4d9b-b1b1-0b3f454c2ffb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='numeric0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#numeric0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>12fe5f01-82ef-4dba-b820-11032d3fef29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>numeric0</value>
      <webElementGuid>6fdaaf0d-ca30-49b9-a79d-b9412689e7f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>numeric0</value>
      <webElementGuid>8e26723b-cb21-4c8f-8023-c4f704ca3316</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>966293fd-5feb-490f-8c99-69d637ace4f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>340b9c4c-7299-437c-b9fe-e8d6b479e49f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>CK-MB</value>
      <webElementGuid>08e3fb3d-2634-48a8-b94e-1eb385fdc90f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minval</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>793860cb-84e4-4092-af76-2d3cd9aea266</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxval</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>3948cd4f-49f5-45df-be42-a0becda89e6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>range_validate(this.value,0,25,0);</value>
      <webElementGuid>8cc1c20e-7c43-4142-9455-8ed12d9edf71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bv-field</name>
      <type>Main</type>
      <value>numeric0</value>
      <webElementGuid>dfe15523-26fe-496a-a654-82f9cf3aaa0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;numeric0&quot;)</value>
      <webElementGuid>39cbae83-fd43-4f50-897d-acbf1a17b411</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='numeric0']</value>
      <webElementGuid>a71b8df6-5c3c-45dc-b9b7-9d1847ada83f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AttributeRow0']/div/div/div[3]/div/input</value>
      <webElementGuid>4568bf52-8189-4b4c-baca-374d18c665a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>008921cc-1dc7-49e1-9b40-7694363fdc66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'numeric0' and @name = 'numeric0' and @type = 'text' and @placeholder = 'CK-MB']</value>
      <webElementGuid>ad4dfea4-6563-46c2-bfe8-b6c37d384ed9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
