<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Please Select Package</name>
   <tag></tag>
   <elementGuidId>a2e8d7be-0bcd-42cf-9f97-06ce868a3488</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-OnPanelOrganizationPackageId-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-OnPanelOrganizationPackageId-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f1cdfa44-c142-4700-be8a-dd072ecef464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>955c61f5-8168-4a06-9913-e702f28418eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-OnPanelOrganizationPackageId-container</value>
      <webElementGuid>24e159d7-654f-4434-8eff-280af22ca551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>bd5bf13c-361e-4707-9797-f8ee7688f872</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>609b3590-c712-4276-a262-e34f188bc2c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Please Select Package</value>
      <webElementGuid>5d301353-93f7-4057-bdde-7467a9b8cd82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please Select Package</value>
      <webElementGuid>8f35f69b-9a03-4a27-b291-2af3fa3c31c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-OnPanelOrganizationPackageId-container&quot;)</value>
      <webElementGuid>23f08b04-6b5c-4f28-a046-dc583efb5098</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-OnPanelOrganizationPackageId-container']</value>
      <webElementGuid>e51698ee-095a-46a9-b641-9f5e4587ac27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myDIV']/div/div[2]/div/div[2]/span/span/span/span</value>
      <webElementGuid>497951dd-90d5-470f-922d-57a4adc46c22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Panel Package'])[1]/following::span[4]</value>
      <webElementGuid>e9c97893-d2d9-43dd-bd07-700fa5c704f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cat-IV By Executive Director'])[2]/following::span[6]</value>
      <webElementGuid>5e9cffe4-8f41-4344-bdb3-f7fba219dfaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Service Package'])[1]/preceding::span[3]</value>
      <webElementGuid>ab86c531-259b-4662-8374-4f6916237f1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Package'])[2]/preceding::span[3]</value>
      <webElementGuid>6fbdeb3b-eb99-466e-97b4-736fd4b253ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/span/span/span/span</value>
      <webElementGuid>17ce9df2-1cfb-4c44-a94d-f46ebf10373d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-OnPanelOrganizationPackageId-container' and @title = 'Please Select Package' and (text() = 'Please Select Package' or . = 'Please Select Package')]</value>
      <webElementGuid>5cf2e04a-edc4-46ce-a0fb-87011c3fb309</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
