<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Testroom1</name>
   <tag></tag>
   <elementGuidId>946711ef-469e-46ea-bbd1-0ca37ea6fe8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='RoomId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#RoomId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>41b126ba-4f6c-40e8-b843-9cce356b08d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectpicker form-control hiddenField</value>
      <webElementGuid>6228ea64-50ce-4224-8fe3-57a2927eeed2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-actions-box</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>86ba5925-81dd-4298-b5f2-97b61f640c41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-live-search</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1a5b5965-374a-44f0-8f8c-f5658028a1c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>RoomId</value>
      <webElementGuid>1e65a4f7-41b8-4b23-87ef-01b954bb2617</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>multiple</name>
      <type>Main</type>
      <value>multiple</value>
      <webElementGuid>e938d0ec-0f0b-47b8-a878-b13ea0fec526</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>RoomId</value>
      <webElementGuid>f195f70c-601b-47e5-a393-fe3b8516dd4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-98</value>
      <webElementGuid>0b4dc3ab-e9f7-40be-a99f-765ec2fe2475</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Testroom1</value>
      <webElementGuid>0f38910a-7485-4fa1-84ce-1c3364078011</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RoomId&quot;)</value>
      <webElementGuid>9bee1247-916e-404a-8b41-91bb01c08ff6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='RoomId']</value>
      <webElementGuid>55e2bb3d-bc3c-47b8-811a-632eaddcb051</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AddDivId']/div[2]/div/div/div[6]/div/div[2]/div/select</value>
      <webElementGuid>c946aa02-3912-47d3-bdec-e08740dde80d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Room'])[1]/following::select[1]</value>
      <webElementGuid>01062c18-64b1-4c8d-84fc-e8fea77ab283</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Testfloor1'])[3]/following::select[1]</value>
      <webElementGuid>957bfb2d-fb63-4b8a-af12-7c35b9a697d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please Select'])[1]/preceding::select[1]</value>
      <webElementGuid>b31ed3fe-9b5a-4041-b807-7a7be25975c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select All'])[3]/preceding::select[1]</value>
      <webElementGuid>6c0c49f9-8fc3-4ce4-b623-b6b429e4b493</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/div/select</value>
      <webElementGuid>f77154be-f3da-417f-a940-6269925bd27e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'RoomId' and @name = 'RoomId' and (text() = 'Testroom1' or . = 'Testroom1')]</value>
      <webElementGuid>48138470-e47f-4021-8460-8ed08b4ab4b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
