<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Invoice No_txtVendorInvoiceNo</name>
   <tag></tag>
   <elementGuidId>e7b290db-974a-487c-b224-032c092d9d7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtVendorInvoiceNo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtVendorInvoiceNo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7cc66ddd-0695-4f91-accb-3f2c0a35fd05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a211d87b-192c-464d-89fc-16b9e3cb517a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6669a74b-b4c1-494d-9ebe-c113b1064499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtVendorInvoiceNo</value>
      <webElementGuid>458dda60-8cb8-44eb-a986-30f29c852cef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtVendorInvoiceNo&quot;)</value>
      <webElementGuid>692fb4a0-d1b2-4cd5-877d-07f2276e6b40</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtVendorInvoiceNo']</value>
      <webElementGuid>1b41da0f-8050-4ee7-ac62-14987fb61bb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_content']/div/div/div[2]/div/div[5]/div/div[2]/input</value>
      <webElementGuid>d4aea297-ac4e-454b-8ab5-085b14f6a32b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/input</value>
      <webElementGuid>da006655-cfe7-42c6-8a01-ab3c79d500db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtVendorInvoiceNo']</value>
      <webElementGuid>bea2156c-3914-4cfd-982a-5a07a51b5ab1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
