<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Challan No_txtChallanNo</name>
   <tag></tag>
   <elementGuidId>f22fcf28-e0bf-40df-a4ad-bc86e1e1d54a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtChallanNo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtChallanNo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d2b358b6-e562-41d2-97f1-7523ff2269dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>caed66d2-aeee-4184-bc9d-36ddd41aae3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>47fc184b-7985-47cd-83b4-2bf7223dfdb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtChallanNo</value>
      <webElementGuid>ace4361a-0ee3-46db-8ad0-03d83d0f6a06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtChallanNo&quot;)</value>
      <webElementGuid>df0f958a-ba90-4de4-91e1-3446be69c699</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtChallanNo']</value>
      <webElementGuid>1cf2ba75-1557-46e5-a9a1-bbf79461421b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_content']/div/div/div[2]/div/div[4]/div[2]/div[2]/input</value>
      <webElementGuid>542fffe4-a904-4023-96d0-9cf4260e68b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>a4dc0cc0-0d91-4316-ba0e-8d3d5a462436</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtChallanNo']</value>
      <webElementGuid>8a3c3858-bf2a-4614-9d23-e31cf96f3703</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
