<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Select Type</name>
   <tag></tag>
   <elementGuidId>25da3166-9d6f-42b2-a5ad-9818734b8d02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-md-2.form-group.mr-0.ml-0.pr-0.pl-1 > div.dropdown.bootstrap-select.form-control.Reset > button.btn.dropdown-toggle.btn-light > div.filter-option > div.filter-option-inner > div.filter-option-inner-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='repeater']/div/div/div/div/div[2]/div/button/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f46498fc-f1bd-4854-8200-04c5a2a62bf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filter-option-inner-inner</value>
      <webElementGuid>b690c309-23c8-431f-bd61-be718f489881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Type</value>
      <webElementGuid>0dca86d9-7b69-44b7-a46e-af028c753425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;repeater&quot;)/div[@class=&quot;row Myrepeater&quot;]/div[@class=&quot;form-horizontal col-md-10 pl-1 pr-1&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-2 form-group mr-0 ml-0 pr-0 pl-1&quot;]/div[@class=&quot;dropdown bootstrap-select form-control Reset&quot;]/button[@class=&quot;btn dropdown-toggle btn-light&quot;]/div[@class=&quot;filter-option&quot;]/div[@class=&quot;filter-option-inner&quot;]/div[@class=&quot;filter-option-inner-inner&quot;]</value>
      <webElementGuid>8648d9a4-07c9-4d28-9c59-df961025c884</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='repeater']/div/div/div/div/div[2]/div/button/div/div/div</value>
      <webElementGuid>12a51fee-97b7-4b2f-bb5a-d6de568f3240</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::div[4]</value>
      <webElementGuid>5eb29530-747f-4765-99b5-2cbd7a1a181f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please select type.'])[1]/preceding::div[4]</value>
      <webElementGuid>a07e72d5-ee24-4b72-953a-5e2129c93abd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unit'])[3]/preceding::div[5]</value>
      <webElementGuid>ba8c26a1-313c-4edb-8033-8726de745101</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button/div/div/div</value>
      <webElementGuid>9c130578-96a6-433b-8a11-2fd3c9e55244</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Select Type' or . = 'Select Type')]</value>
      <webElementGuid>d8937ddf-7ca1-46af-9bc7-0050f919f6e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
