<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Ip</name>
   <tag></tag>
   <elementGuidId>971cd772-2ec9-443d-ac23-1810e6bc85fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#IpId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='IpId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ea32bbab-93b5-49e7-a3a3-0e2d974f0091</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>IpId</value>
      <webElementGuid>3d166ebd-4e33-42e2-9ddd-bf35a5e726fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Ip</value>
      <webElementGuid>8dc14a2f-fd65-48e2-943e-db0112e66689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>360622a4-1540-4e26-8886-0b444a75b125</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>607c59cd-ad3e-465a-8cac-4c67fcde63b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2561b151-3d93-4c48-92cd-23d149ed1ccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>39f7df04-6561-4638-b48d-ff9bfee86aca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>IP</value>
      <webElementGuid>12205c5e-6c28-44f0-b3ab-930d407763e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bv-field</name>
      <type>Main</type>
      <value>Ip</value>
      <webElementGuid>03cd7ca3-1497-4c2b-91d2-24d18b0546f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IpId&quot;)</value>
      <webElementGuid>3e9fce0b-cc78-4eb6-bae2-0e131845a2f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='IpId']</value>
      <webElementGuid>d85146b8-cc37-4c5a-bc1a-b0ece9684f75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AddDivId']/div[2]/div/div[2]/div/div/div[2]/input</value>
      <webElementGuid>c8dd7946-a8c3-4b91-a84c-921a12a48152</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/input</value>
      <webElementGuid>7b23ec5d-a035-42f4-b238-5afc995a56d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'IpId' and @name = 'Ip' and @type = 'text' and @placeholder = 'IP']</value>
      <webElementGuid>aa64d93f-400d-49f9-97d0-6f1c936490c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
