<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ul_Select StoreAcademic Affair StoreAccount_8b5e9d_1</name>
   <tag></tag>
   <elementGuidId>97fd0bed-e0db-4ef7-af4f-761a8b757550</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-ToStoreId-results</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='select2-ToStoreId-results']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
      <webElementGuid>4b51032f-b61b-4b74-892a-46a1c8820ccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__options</value>
      <webElementGuid>d69ae6dd-191c-4fa1-9a4f-8b94742d3cda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>2dd05298-c4eb-4fdd-ab73-df8709bc693f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-ToStoreId-results</value>
      <webElementGuid>26fb10bb-bf40-427b-9a6d-f2d6f2e576cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>162ca02e-382e-4250-bfa0-675a037a5710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b6231f2c-9dcf-4d4e-8ed9-96e6dc7809b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select StoreAcademic Affair StoreAccounts StoreAdmin &amp; Security StoreAdmin StoreasdBait ul Maal StoreBio Gases StoreBiomedical StoreCash Store (Accounts)Cath Lab StoreCath Lab Store MPCCTV StoreCCU-1 StoreConference StoreCook StoreCoronary Care Unit-2 StoreCSSD StoreCT-Angio StoreDay Care StoreDDC StoreDental StoreDMS Admin StoreDoctor Hostel StoreECG StoreEcho StoreED Office StoreED OPD StoreElectric StoreEmergency Medicine StoreEmergency MP StoreEP StoreERC StoreETT StoreExchange StoreFiltration Plant StoreFinance StoreGardener StoreGeneral StoreGeneral Ward StoreGenerator StoreGynae Ward StoreHDU-2 StoreHostel StoreHvac StoreIncinerator StoreIntensive Care Unit Store (ITC)IPD PharmacyIT Department StoreITC III StoreLaboratory StoreLaundryLibrary StoreLift storeLP StoreMain Disposable StoreMain Laboratory StoreMain Stock &amp; Accessories StoreMain Store Cath LabMatron StoreMedicine StoreModel Pharmacy Main StoreModel Pharmacy StoreModelPharmacyMP Cardiac Medicine StoreMP ITC/ICU StoreMRIMS Office StoreMSDS StoreNeurology StoreNuclear Medicine StoreNursing Hostel StoreOPD PharmacyOPD Reception StoreOPD StoreOT Anesthesia StoreOT Medicine and Disposible StoreOT Perfusion StoreOT Store GeneralOT Store MedicineOT Store MPOT Surgery StoreP &amp; D StorePaeds Ward StorePainter StorePhysiotherapy StorePlumber StorePost Cath 1 &amp; 2 StorePreload StorePrimary PCI StorePrivatePrivate Surgical Ward StorePsychology StorePurchase StoreRadiology MP StoreRadiology StoreRecord Room StoreRepeat Medicine StoreSatellite Pharmacy Cath LabSatellite Pharmacy ERSatellite Pharmacy OTSpecial Private Ward StoreSSP  StoreSurgical Ward StoreTac storetailor StoreTechnical StoreTransport StoreTube Well StoreVIP Storewqertyj</value>
      <webElementGuid>7a2d75d3-c6fa-4dc5-b37c-c153580994cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-ToStoreId-results&quot;)</value>
      <webElementGuid>715ffb46-11ae-4a4c-a1d3-150db58595f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//ul[@id='select2-ToStoreId-results']</value>
      <webElementGuid>df3101fa-116a-417e-b370-5be483833a5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'select2-ToStoreId-results', '&quot;', ')')])[1]/following::ul[1]</value>
      <webElementGuid>d2b4a529-3b18-458e-a863-bfe5517f4c9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Set Waiting Time'])[1]/following::ul[1]</value>
      <webElementGuid>18a7cfb5-fdb7-474d-8116-1d1b83e172b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/ul</value>
      <webElementGuid>503a4790-1bd6-4687-8a58-24271d735251</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ul[@id = 'select2-ToStoreId-results' and (text() = 'Select StoreAcademic Affair StoreAccounts StoreAdmin &amp; Security StoreAdmin StoreasdBait ul Maal StoreBio Gases StoreBiomedical StoreCash Store (Accounts)Cath Lab StoreCath Lab Store MPCCTV StoreCCU-1 StoreConference StoreCook StoreCoronary Care Unit-2 StoreCSSD StoreCT-Angio StoreDay Care StoreDDC StoreDental StoreDMS Admin StoreDoctor Hostel StoreECG StoreEcho StoreED Office StoreED OPD StoreElectric StoreEmergency Medicine StoreEmergency MP StoreEP StoreERC StoreETT StoreExchange StoreFiltration Plant StoreFinance StoreGardener StoreGeneral StoreGeneral Ward StoreGenerator StoreGynae Ward StoreHDU-2 StoreHostel StoreHvac StoreIncinerator StoreIntensive Care Unit Store (ITC)IPD PharmacyIT Department StoreITC III StoreLaboratory StoreLaundryLibrary StoreLift storeLP StoreMain Disposable StoreMain Laboratory StoreMain Stock &amp; Accessories StoreMain Store Cath LabMatron StoreMedicine StoreModel Pharmacy Main StoreModel Pharmacy StoreModelPharmacyMP Cardiac Medicine StoreMP ITC/ICU StoreMRIMS Office StoreMSDS StoreNeurology StoreNuclear Medicine StoreNursing Hostel StoreOPD PharmacyOPD Reception StoreOPD StoreOT Anesthesia StoreOT Medicine and Disposible StoreOT Perfusion StoreOT Store GeneralOT Store MedicineOT Store MPOT Surgery StoreP &amp; D StorePaeds Ward StorePainter StorePhysiotherapy StorePlumber StorePost Cath 1 &amp; 2 StorePreload StorePrimary PCI StorePrivatePrivate Surgical Ward StorePsychology StorePurchase StoreRadiology MP StoreRadiology StoreRecord Room StoreRepeat Medicine StoreSatellite Pharmacy Cath LabSatellite Pharmacy ERSatellite Pharmacy OTSpecial Private Ward StoreSSP  StoreSurgical Ward StoreTac storetailor StoreTechnical StoreTransport StoreTube Well StoreVIP Storewqertyj' or . = 'Select StoreAcademic Affair StoreAccounts StoreAdmin &amp; Security StoreAdmin StoreasdBait ul Maal StoreBio Gases StoreBiomedical StoreCash Store (Accounts)Cath Lab StoreCath Lab Store MPCCTV StoreCCU-1 StoreConference StoreCook StoreCoronary Care Unit-2 StoreCSSD StoreCT-Angio StoreDay Care StoreDDC StoreDental StoreDMS Admin StoreDoctor Hostel StoreECG StoreEcho StoreED Office StoreED OPD StoreElectric StoreEmergency Medicine StoreEmergency MP StoreEP StoreERC StoreETT StoreExchange StoreFiltration Plant StoreFinance StoreGardener StoreGeneral StoreGeneral Ward StoreGenerator StoreGynae Ward StoreHDU-2 StoreHostel StoreHvac StoreIncinerator StoreIntensive Care Unit Store (ITC)IPD PharmacyIT Department StoreITC III StoreLaboratory StoreLaundryLibrary StoreLift storeLP StoreMain Disposable StoreMain Laboratory StoreMain Stock &amp; Accessories StoreMain Store Cath LabMatron StoreMedicine StoreModel Pharmacy Main StoreModel Pharmacy StoreModelPharmacyMP Cardiac Medicine StoreMP ITC/ICU StoreMRIMS Office StoreMSDS StoreNeurology StoreNuclear Medicine StoreNursing Hostel StoreOPD PharmacyOPD Reception StoreOPD StoreOT Anesthesia StoreOT Medicine and Disposible StoreOT Perfusion StoreOT Store GeneralOT Store MedicineOT Store MPOT Surgery StoreP &amp; D StorePaeds Ward StorePainter StorePhysiotherapy StorePlumber StorePost Cath 1 &amp; 2 StorePreload StorePrimary PCI StorePrivatePrivate Surgical Ward StorePsychology StorePurchase StoreRadiology MP StoreRadiology StoreRecord Room StoreRepeat Medicine StoreSatellite Pharmacy Cath LabSatellite Pharmacy ERSatellite Pharmacy OTSpecial Private Ward StoreSSP  StoreSurgical Ward StoreTac storetailor StoreTechnical StoreTransport StoreTube Well StoreVIP Storewqertyj')]</value>
      <webElementGuid>c87d1375-21a2-4495-93bd-192a9f88a684</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
