<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Name</name>
   <tag></tag>
   <elementGuidId>f939b5d6-36b6-415c-b149-cde04cead5f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>260940c1-d1c0-4b5c-b42e-632fd67b9188</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>d16a26d5-6ae0-4ca7-8bc1-96ea3c2fbe35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>f1e7589d-3aab-4ce5-9112-d5ae8668ce8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>Utilities.TakeOnlyNormalValidInput(this)</value>
      <webElementGuid>c4e8235c-a415-4944-b1e2-a66e285e37cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>1181c923-b440-49e9-95e4-67b5c42272e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>83b03f8b-d5ae-43d7-85a2-24ee8363dd4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>this.value=this.value.replace(/[^a-zA-Z' ']/g, '')</value>
      <webElementGuid>db342de9-9d3e-4654-9555-f857ef2d2b30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9b94f0f4-876f-4cfc-a59f-8414e095fac8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>93554f7a-cdfd-400f-b05e-92bedd3f16fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bv-field</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>cf040f02-26f9-449d-8061-3ee267563756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Name&quot;)</value>
      <webElementGuid>10464bdd-592c-44cc-b2b6-cef5a932b54c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Name']</value>
      <webElementGuid>b96563f6-aad6-4a73-8905-06aa552e229d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myDIV']/div[2]/div/div/div[2]/div[2]/input</value>
      <webElementGuid>6b784154-77f7-442b-8a1c-1a9196ac912b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>06d12daf-3720-4f4d-97b8-a7ab9e3af141</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Name' and @name = 'Name' and @type = 'text' and @placeholder = 'Name']</value>
      <webElementGuid>67290bc9-a931-4071-9718-fc08000ea146</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
