<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Please enter valid procedure duration_5d2bad</name>
   <tag></tag>
   <elementGuidId>34668763-73b0-4153-b3e7-519f614cb270</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BookProcedureButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='BookProcedureButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c11cc905-52bd-40f0-9691-9b3566bd1831</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d39bc4ef-4d8d-4d8e-97cd-c401ab71f313</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BookProcedureButton</value>
      <webElementGuid>61012a62-2b92-4fa8-9b00-cd00706f6e73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Book Procedure</value>
      <webElementGuid>a17ffeaa-f947-4798-b591-6c48200cf8bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>38696e6a-a28e-4d49-bd5a-a5ca9f84e9e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BookProcedureButton&quot;)</value>
      <webElementGuid>15a46c81-7b01-49ae-85ff-011ca6e77a99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='BookProcedureButton']</value>
      <webElementGuid>c02706d4-c01a-46bd-bb81-8c24e1eb75be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='ProcedureBooking']/div[2]/input</value>
      <webElementGuid>e2321cd6-d2db-4d8f-875e-74ab80ef981a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/input</value>
      <webElementGuid>9fdbb21c-4a75-4f56-a839-5013fce8459d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'BookProcedureButton']</value>
      <webElementGuid>7d8fde25-bfeb-4c48-b0c3-c18f2f54e47f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
