<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_82401-2464218-9Mr. Sajid Mehmoodd</name>
   <tag></tag>
   <elementGuidId>6607a01d-d196-44f9-8844-3f71b3771ebf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='bs-select-5-0']/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bs-select-5-0 > span.text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9957194e-9cdc-4973-93b4-602f04864565</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>51bcc0e4-0d58-4468-87eb-daaaeeb315e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>82401-2464218-9:Mr. Sajid Mehmoodd</value>
      <webElementGuid>42570a63-c3e6-43c3-b0ec-55ce5f2c853a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bs-select-5-0&quot;)/span[@class=&quot;text&quot;]</value>
      <webElementGuid>afff67d3-1b2f-4b5c-9f1b-970030a10570</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='bs-select-5-0']/span[2]</value>
      <webElementGuid>da218bbf-cd58-4bc1-9fd9-9d2853093a94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deselect All'])[5]/following::span[2]</value>
      <webElementGuid>88c4250d-ef4a-4e2b-82e0-6f821dc5331d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select All'])[5]/following::span[2]</value>
      <webElementGuid>67e0fb3a-bcb9-4245-8745-a20798bb1da0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Salary Stage'])[1]/preceding::span[31]</value>
      <webElementGuid>a9adfecb-9df9-496d-bd1a-b0dcab10ed13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please enter a value greater than or equal to %s'])[1]/preceding::span[31]</value>
      <webElementGuid>3f2664e2-68a8-44bc-b842-6adb29401fe3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[2]/div/div/div[3]/ul/li/a/span[2]</value>
      <webElementGuid>7fa6b3bb-549e-4fb7-83af-0eec756a7035</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '82401-2464218-9:Mr. Sajid Mehmoodd' or . = '82401-2464218-9:Mr. Sajid Mehmoodd')]</value>
      <webElementGuid>5e44e812-76df-4832-b075-a709c2acd999</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
