<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sign In</name>
   <tag></tag>
   <elementGuidId>8084e371-8b73-4773-956d-3c483f4adda3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#kt_login_signin_submit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='kt_login_signin_submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a4443bee-1249-4d7a-ae51-26372f26a936</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>kt_login_signin_submit</value>
      <webElementGuid>c242f14a-0b31-4b4f-9988-76fd8150e5a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>kt_login_signin_submit</value>
      <webElementGuid>76c2f8f3-1e08-49bd-8ae4-0d693a6ec31c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>login</value>
      <webElementGuid>06e66c89-4820-4f40-b079-4afa2f1e5432</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-elevate kt-login__btn-primary</value>
      <webElementGuid>ce017a78-a6eb-4440-beb3-375cc79a4e4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign In</value>
      <webElementGuid>e338348b-cbed-4c21-b2fb-c8efe31a776b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_login_signin_submit&quot;)</value>
      <webElementGuid>4bf31d8c-903d-4d63-bc35-46597864594c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='kt_login_signin_submit']</value>
      <webElementGuid>134c48d5-51b9-487b-bd28-aa9f9f29fa2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='kt_login_form']/div[3]/button</value>
      <webElementGuid>17a43e8b-a1e3-4906-b1f5-1055f2515ff5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot Password ?'])[1]/following::button[1]</value>
      <webElementGuid>fdf6982b-8509-44ab-a734-0c219a7e2ab1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign In'])[1]/following::button[1]</value>
      <webElementGuid>28feac30-c0ad-4a20-a847-966c755b6dd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'kt_login_signin_submit', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>f1c28d6c-07b3-4afd-835d-f0cb78aecd8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>a760a094-7bad-42fd-b1c1-f2cea628b420</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'kt_login_signin_submit' and @name = 'kt_login_signin_submit' and (text() = 'Sign In' or . = 'Sign In')]</value>
      <webElementGuid>b50c2877-10e0-41ff-90de-5a58f0f29956</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
