<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select Job Type</name>
   <tag></tag>
   <elementGuidId>fc598cbe-0a18-42ec-91b7-2501e0846406</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-JobTypeId-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-JobTypeId-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5dcd8ae6-ad55-43f6-924b-645f31b52053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>be990d2f-db1e-4f70-9f6a-2da5ef24fb24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-JobTypeId-container</value>
      <webElementGuid>b5d31e67-61c6-410e-9346-eabee2eae617</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>924bdf13-cf38-43e8-be0e-b2146f677383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>48ec5d69-efb1-496e-bf1e-a6578dc3f139</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Select Job Type</value>
      <webElementGuid>117da691-3625-4abf-bbb7-a62f987aae87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Job Type</value>
      <webElementGuid>428f9cbc-0525-4db0-be89-b5909262564f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-JobTypeId-container&quot;)</value>
      <webElementGuid>c08ea1be-d06a-4153-8212-c9afff4098cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-JobTypeId-container']</value>
      <webElementGuid>6da90638-1821-4a94-88aa-fecce7f5ab22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='UpdateSalarySatageForm']/div/div[2]/div/div[2]/span/span/span/span</value>
      <webElementGuid>22567dff-8759-4245-a94c-e8669c3770e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Job Type'])[1]/following::span[4]</value>
      <webElementGuid>61f5fa9d-76de-4465-8fbc-6560e5cd15a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please Select Scale'])[1]/following::span[4]</value>
      <webElementGuid>88a04591-c4b1-4419-894b-039350a3e0ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employee'])[1]/preceding::span[3]</value>
      <webElementGuid>3ed6aaf5-13c3-440a-b2fe-3fe2c1f4e572</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Employee'])[2]/preceding::span[3]</value>
      <webElementGuid>35d69d55-6fac-441a-9fd4-eb38c75579ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/span/span/span/span</value>
      <webElementGuid>eb330ed9-9f2f-43b0-a6df-62ef40821328</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-JobTypeId-container' and @title = 'Select Job Type' and (text() = 'Select Job Type' or . = 'Select Job Type')]</value>
      <webElementGuid>e2f1e07b-fc7f-48a4-99b2-c6326d0437f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
