<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select Scale</name>
   <tag></tag>
   <elementGuidId>bb274d22-2b60-492c-b769-43ac54ba8da9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-ScaleID-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-ScaleID-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>aa5b6ae6-f823-4d5e-9c0e-0037dc6fdd48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>733d513b-4ce8-44ee-8aac-93b635f73a4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-ScaleID-container</value>
      <webElementGuid>6910ff26-5c5d-4296-a6a4-b753240496bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>6785bf16-6064-4fc6-8282-b02d97a1644d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f9cc560b-11df-456d-8b2b-cae102870ebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Select Scale</value>
      <webElementGuid>6c618450-8ee1-4e40-9048-afcd9b3f9a42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Scale</value>
      <webElementGuid>9ee1aac7-bba1-4e12-8429-267ad69dfc7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-ScaleID-container&quot;)</value>
      <webElementGuid>ce5f8850-7150-4539-9509-46c21cd07f01</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-ScaleID-container']</value>
      <webElementGuid>c688564b-e0ca-4104-a2a0-6b27e9bb0579</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='UpdateSalarySatageForm']/div/div/div/div[2]/span/span/span/span</value>
      <webElementGuid>c4f92a2f-15a4-4c08-85f9-11ee7813f8fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::span[4]</value>
      <webElementGuid>8ea65cab-879e-4b0b-99cd-de0dfdd5de37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please Select Scale'])[1]/preceding::span[3]</value>
      <webElementGuid>f5710fb9-3e7b-484a-a04c-49fb5f28aa05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Job Type'])[1]/preceding::span[3]</value>
      <webElementGuid>3ba38b60-3cff-4dc2-a0a3-2644a03be50e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>9e8c23ba-e350-41be-a0dd-b14db08071af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-ScaleID-container' and @title = 'Select Scale' and (text() = 'Select Scale' or . = 'Select Scale')]</value>
      <webElementGuid>e3e92cd9-a806-4ccc-875e-2a3cdcf68b76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
