<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__ExpenseCategoryName</name>
   <tag></tag>
   <elementGuidId>e2d5c009-3ace-4f33-9a42-d62d9937c9aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ExpenseCategoryName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ExpenseCategoryName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a921f45e-b40d-4be1-9396-b76a56d3b98d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ExpenseCategoryName</value>
      <webElementGuid>05180118-4618-43b0-a44e-146f3406f927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ExpenseCategoryName</value>
      <webElementGuid>d0795f0d-07b2-4f02-9c46-a85debe5f31b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>Utilities.TakeOnlyNormalValidInput(this)</value>
      <webElementGuid>bfa29c8f-34f6-48ac-8b1d-2c99669e0598</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>6c9c1d0c-b26e-4db5-892e-57a4a42eba4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fc5b32b0-0567-46ce-9c36-a4d8eca2b3fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>58195d79-02bf-4dda-9f14-cbb5522488c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>9bb7f074-6e60-4131-91dc-9b6bbb684556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bv-field</name>
      <type>Main</type>
      <value>ExpenseCategoryName</value>
      <webElementGuid>ec5ad55c-007e-49a0-b7b2-e790c2743ad1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ExpenseCategoryName&quot;)</value>
      <webElementGuid>507bb40b-754a-4535-b592-2b98378dc890</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ExpenseCategoryName']</value>
      <webElementGuid>386d9b13-d444-495b-9c4c-094adc32fc17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myDIV']/div/div/div[3]/div[2]/input</value>
      <webElementGuid>e976e091-270e-4f7f-8a2e-8a4376b6874c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>8d6b6b5c-7bfd-4960-9606-133edc5c2211</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ExpenseCategoryName' and @name = 'ExpenseCategoryName' and @type = 'text' and @placeholder = 'Name']</value>
      <webElementGuid>404859ef-ae1a-45f7-84cb-670ec8857814</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
