<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__ExpenseCategoryCode</name>
   <tag></tag>
   <elementGuidId>18c82957-b410-4cbc-b1d0-60b771b4ec03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ExpenseCategoryCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ExpenseCategoryCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8d0917af-2f97-4029-943c-b8e4665d111b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ExpenseCategoryCode</value>
      <webElementGuid>3f474d17-460a-432c-9592-f49ec9242547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ExpenseCategoryCode</value>
      <webElementGuid>44d1e6cc-8d7d-4b91-ab76-29f6f2a42e36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>Utilities.TakeOnlyNormalValidInput(this)</value>
      <webElementGuid>1c61b7d5-8c07-4f1e-815f-b2880550dda2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>1ba8f71b-828e-4c34-b630-86c570d558fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6ed5098f-5c54-4be8-83be-4a14fcbd2009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>5e02e742-175b-48e3-90d6-a5bdb5750afa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Code</value>
      <webElementGuid>7fa50102-2981-457d-93ab-46c3edee4d98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bv-field</name>
      <type>Main</type>
      <value>ExpenseCategoryCode</value>
      <webElementGuid>6b2787b3-3e74-411e-8f38-f16faf298335</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ExpenseCategoryCode&quot;)</value>
      <webElementGuid>6fa4e400-5bd4-4cf5-8861-c54aef014d08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ExpenseCategoryCode']</value>
      <webElementGuid>b461ec29-a96e-48d9-849a-42850b584250</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myDIV']/div/div/div[2]/div[2]/input</value>
      <webElementGuid>b88bbe91-a401-4655-a620-92ee73b05f3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>ef1027bc-82c0-4307-9804-69eeafe2bead</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ExpenseCategoryCode' and @name = 'ExpenseCategoryCode' and @type = 'text' and @placeholder = 'Code']</value>
      <webElementGuid>7b573c4f-4ce9-41d8-b58a-819cbeae5b75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
