<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ul_SearchingBD twice daily    HS at bed tim_e83dbc</name>
   <tag></tag>
   <elementGuidId>f50879db-b88a-4ba2-ba75-e18e92619303</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-MedicineDosageId-results</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='select2-MedicineDosageId-results']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
      <webElementGuid>78fcd95e-d42e-41cf-b841-82b0ce3d9b64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__options</value>
      <webElementGuid>ce0c1438-3e3f-403a-bce7-d0c533bf46a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>45aae690-2c76-4e99-b93a-01776c89c8b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-MedicineDosageId-results</value>
      <webElementGuid>d772d085-de6c-4ee2-b443-81f00dffdc47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ecc3f022-fe41-442f-a592-ff5a453f16f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9521e31f-d709-4a45-a903-324cad8e3cd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Searching…BD twice daily دن میں دو مرتبہHS at bed time رات کو سونے سے پہلے OD once daily دن میں ایک مرتبہQ.M Once in month مہینے میں ایک دفعہQ.O.D. every other day ہر دوسرے دنq12h every 12 hours ہر بارہ گھنٹے کے بعدq1h every 1 hours ہر ایک گھنٹے کے بعد</value>
      <webElementGuid>4cc5dfa8-b8cc-4b39-be15-414369e581b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-MedicineDosageId-results&quot;)</value>
      <webElementGuid>06dd5539-af6b-4790-a2fd-6dd0bb4ffb07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//ul[@id='select2-MedicineDosageId-results']</value>
      <webElementGuid>9857f482-dfda-4512-b590-a71df4990871</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'select2-MedicineDosageId-results', '&quot;', ')')])[1]/following::ul[1]</value>
      <webElementGuid>689e3c81-23c1-4c07-a8e3-51cddda7477d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Set Waiting Time'])[1]/following::ul[1]</value>
      <webElementGuid>060dd08b-ea2a-4ec6-bd19-201af68871f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/ul</value>
      <webElementGuid>252ab3d0-3e26-47d7-bc49-ca6373691855</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ul[@id = 'select2-MedicineDosageId-results' and (text() = 'Searching…BD twice daily دن میں دو مرتبہHS at bed time رات کو سونے سے پہلے OD once daily دن میں ایک مرتبہQ.M Once in month مہینے میں ایک دفعہQ.O.D. every other day ہر دوسرے دنq12h every 12 hours ہر بارہ گھنٹے کے بعدq1h every 1 hours ہر ایک گھنٹے کے بعد' or . = 'Searching…BD twice daily دن میں دو مرتبہHS at bed time رات کو سونے سے پہلے OD once daily دن میں ایک مرتبہQ.M Once in month مہینے میں ایک دفعہQ.O.D. every other day ہر دوسرے دنq12h every 12 hours ہر بارہ گھنٹے کے بعدq1h every 1 hours ہر ایک گھنٹے کے بعد')]</value>
      <webElementGuid>3f545717-c892-4bac-b14c-9b88bd8396e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
