<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__CellNumber</name>
   <tag></tag>
   <elementGuidId>6378b4f8-8cfc-402f-92ba-791f0b7ad487</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CellNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CellNumber</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2feea78d-9214-49c5-81c0-ecdbd571ca34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CellNumber</value>
      <webElementGuid>27a9b1cb-7d89-4652-a20c-11d034711f8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>31f63e62-8889-44a3-846c-0809a6dad175</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CellNumber</value>
      <webElementGuid>ad33c6d2-fdba-4435-8844-e5eff2ee5bdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4160f9b8-7445-41c1-a6e6-0614366ada49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>73a03cb4-a5b2-4ba3-bb46-c891eb079257</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>bee7ef60-a843-43da-b1cb-54a13231f641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>03001234567</value>
      <webElementGuid>982a2c81-0eed-4f58-a071-b72cd5ccc2b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>IS_iNTT(this)</value>
      <webElementGuid>b597b1b8-9098-454d-94a7-a4d90c4f9597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bv-field</name>
      <type>Main</type>
      <value>CellNumber</value>
      <webElementGuid>2eadb446-6184-4429-aafd-ecb04cfff21a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CellNumber&quot;)</value>
      <webElementGuid>a674c08a-d52c-4e0d-a4b9-bdbd895e54bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CellNumber']</value>
      <webElementGuid>9f2fc6c6-1a68-41dc-86b8-1ac501826408</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UserEducationDatatableDiv']/div[2]/div/div[7]/div/div[2]/input</value>
      <webElementGuid>d9f1f84d-c011-4dbf-ad8c-dff292a76bd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div[2]/input</value>
      <webElementGuid>3f4ed5ef-fa5a-4a26-af02-5c6935c7ed69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'CellNumber' and @type = 'text' and @name = 'CellNumber' and @placeholder = '03001234567']</value>
      <webElementGuid>2b245a0a-0682-4e3d-8f8e-c2361c3c701b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
