<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Please enter a value with valid lengt_bf4d4b</name>
   <tag></tag>
   <elementGuidId>bb25d721-3f0e-4680-8f35-5d0a6d7f2bcc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SubmitPatient</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='SubmitPatient']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8af6bf70-888d-4e0f-bbe0-b3f7ec3a66b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SubmitPatient</value>
      <webElementGuid>5803ba44-7117-458a-9d97-acd9252282be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9d7f3502-c8fb-4de8-a7f4-b7f4c819510b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Check In</value>
      <webElementGuid>c9aac092-d4cf-4755-a6a7-2b6392064597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary pull-right</value>
      <webElementGuid>a1aa78df-5364-4190-9e6b-5f3efab6c153</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SubmitPatient&quot;)</value>
      <webElementGuid>cfb41d79-de6a-4f18-b744-48109814c4d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='SubmitPatient']</value>
      <webElementGuid>9c862c26-a313-4ac0-bc7f-cd41c0fccdf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CheckedInDiv_Wrapper']/div[5]/div[2]/input</value>
      <webElementGuid>befb34c1-8ba2-47db-b379-f6958a1b556c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/input</value>
      <webElementGuid>085189fb-42f1-43dc-92dd-f8365298c015</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'SubmitPatient' and @type = 'button']</value>
      <webElementGuid>9f11ca9b-0ec8-4a91-aadd-0653ab45fa87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
