<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_PDF</name>
   <tag></tag>
   <elementGuidId>aa62ebc7-545d-4dc8-9d41-7885d92b0691</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='BtnGetReportPdf']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#BtnGetReportPdf</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>878e85ab-15a6-473c-83a1-7f5ce7844a7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8c9185f5-1c5d-4806-ae75-08be5fb4af1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BtnGetReportPdf</value>
      <webElementGuid>ba0c55af-2caf-4e09-b716-0cbefa93da8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn btn-default</value>
      <webElementGuid>0acd6c04-30aa-4fd7-a767-f615c165ad81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>   PDF</value>
      <webElementGuid>0c7abb0b-f97a-496d-8ee3-b3532d576808</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BtnGetReportPdf&quot;)</value>
      <webElementGuid>4d5fce2c-7448-46ba-adba-8057fa677197</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='BtnGetReportPdf']</value>
      <webElementGuid>d3532876-86e4-423f-a138-3795c03020d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_content']/div/div[3]/div[2]/div[2]/div/div/div/div/div/button</value>
      <webElementGuid>2000a0ee-353f-4ee1-99b1-8d5e721381c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RI-4546 (1173751668)'])[2]/following::button[1]</value>
      <webElementGuid>0a084edb-0bf2-4adc-a568-f2395e92a39c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Bank:'])[1]/following::button[1]</value>
      <webElementGuid>4483e524-297a-412f-b6c1-3513fe8ce5e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[2]/div/div/div/div/div/button</value>
      <webElementGuid>de325630-4db7-4794-951c-18828c1ccb35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'BtnGetReportPdf' and (text() = '   PDF' or . = '   PDF')]</value>
      <webElementGuid>09b19b2b-c381-43e7-8c17-1ee3e58fc4d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
