<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Reverse Day Close</name>
   <tag></tag>
   <elementGuidId>62986afe-9d8f-4280-9d7b-f58bfef78b21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn_ReverseDayClose']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn_ReverseDayClose</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0b1dee78-9ef8-4f16-81eb-d46662fadfda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_ReverseDayClose</value>
      <webElementGuid>43eecbfe-f980-4a79-b02a-cfea76d5a898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>668382cd-8854-4708-a1e5-712f80f3e0ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default btn-icon-sm</value>
      <webElementGuid>06341e5c-3cfc-4f18-a6cf-c008c4d350be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>496c62ed-2e29-47ec-a0bb-2e6cf652dfe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>874e3a5b-bc53-4f34-bd41-5aeca21219ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                Reverse Day Close
                            </value>
      <webElementGuid>2822e734-7ea5-411f-a550-30cdb6db6d91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_ReverseDayClose&quot;)</value>
      <webElementGuid>9f47c9be-ac45-49ef-88c9-3484c181b7d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn_ReverseDayClose']</value>
      <webElementGuid>3e2d7dfa-b3d8-4284-abe7-08f4f679d0fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AddDivId']/div[3]/div/div/div/div/button[2]</value>
      <webElementGuid>ea177099-f82b-4701-81a3-cb8f9e219583</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/following::button[2]</value>
      <webElementGuid>b488629e-55e6-4202-b043-55fbf7a954d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/preceding::button[1]</value>
      <webElementGuid>d16a3d53-2aed-4179-b1e6-2a506b96f904</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Reverse Day Close']/parent::*</value>
      <webElementGuid>56cfea8e-b25c-466d-aa23-5ab7457e8de5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/button[2]</value>
      <webElementGuid>48e06942-e611-4105-862f-b487dc2dd501</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn_ReverseDayClose' and @type = 'button' and (text() = '
                                Reverse Day Close
                            ' or . = '
                                Reverse Day Close
                            ')]</value>
      <webElementGuid>ad099115-ce7c-4d51-98c6-bcdd071a5132</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
