<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Open Field</name>
   <tag></tag>
   <elementGuidId>817569da-6c4b-40bc-a2f4-00fd6db91f55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bs-select-9-5 > span.text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='bs-select-9-5']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>679c142f-f8d8-4dc4-9199-d45e9ee197a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bf73c619-19c5-46de-a8ce-3878a668dc59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Open Field</value>
      <webElementGuid>44f1e96e-e0f0-4daf-b63d-dd3db7a66bdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bs-select-9-5&quot;)/span[@class=&quot;text&quot;]</value>
      <webElementGuid>f38674a9-177e-4582-9455-9830f943b35b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='bs-select-9-5']/span</value>
      <webElementGuid>9ad0eb73-881b-4765-959b-778e66cd3986</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Shelf Life Deduction'])[3]/following::span[5]</value>
      <webElementGuid>adbd2d37-c985-4088-a032-a9a152d269a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Shelf Life Deduction'])[2]/following::span[6]</value>
      <webElementGuid>5f997aef-7c40-48a9-818a-c3d2f4588ecc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please enter a value greater than or equal to %s'])[5]/preceding::span[1]</value>
      <webElementGuid>505e333f-eb75-4adc-9c4f-96438ee1db0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please enter a value less than or equal to %s'])[5]/preceding::span[1]</value>
      <webElementGuid>1989f164-b7c5-4ac9-80e9-7b2ed6af32c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/div/div/div[2]/div/div/div[2]/ul/li[6]/a/span</value>
      <webElementGuid>32fa3a8a-a4c6-4f72-b73e-d1ccf8d9ec80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Open Field' or . = 'Open Field')]</value>
      <webElementGuid>80c64735-4e7e-4c08-8f01-2de47386e85d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
