<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_PDF</name>
   <tag></tag>
   <elementGuidId>ec65dde0-26a0-44b0-9cc5-1e97bdfcbe4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='BtnGetReportPdf']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#BtnGetReportPdf</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>68c50ede-21c5-4be9-a610-5af07b8be0d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5daaef43-a821-4534-85c5-b51e184ac4e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BtnGetReportPdf</value>
      <webElementGuid>d1f3fd0a-a896-431a-9259-9a511872bf5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn btn-default</value>
      <webElementGuid>939f5bf6-b2a2-475a-bfce-e7f9d2ad6feb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>   PDF</value>
      <webElementGuid>0acbe7bb-a186-4bbb-bcbd-4b2f23de5b52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BtnGetReportPdf&quot;)</value>
      <webElementGuid>d114911c-bb16-40d7-be62-e98d1832d4ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='BtnGetReportPdf']</value>
      <webElementGuid>14f667de-a59e-4c7e-9670-1cb8acb8556e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_content']/div/div[3]/div[2]/div[3]/div/div/div/div/div/button</value>
      <webElementGuid>4cc41f57-fd2d-4dea-8461-a0ef8554d79f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/button</value>
      <webElementGuid>5ce2a6fa-9779-4830-a5a8-930da2f2074a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'BtnGetReportPdf' and (text() = '   PDF' or . = '   PDF')]</value>
      <webElementGuid>e159a833-c326-4fcc-9320-ebb739db3e9b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
