<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Check Out</name>
   <tag></tag>
   <elementGuidId>951cd275-2536-4f55-8d3b-c02d81b2eb06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#IsManualEmployeeTimeOut</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='IsManualEmployeeTimeOut']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7bae857a-9f3e-418a-89a0-c764f8181659</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f9ddd72b-fe80-483b-8b25-c3d23300dd55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>IsManualEmployeeTimeOut</value>
      <webElementGuid>93a97877-eb31-4e92-a7de-a343887d2ba2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-danger</value>
      <webElementGuid>bae61aee-e115-4bb9-9900-af2d3d4a3343</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Check Out</value>
      <webElementGuid>b70a4504-1c69-4fb0-82cc-98b3ad1ff8f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IsManualEmployeeTimeOut&quot;)</value>
      <webElementGuid>526d8a1f-3c0b-47ed-868c-f263477559fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='IsManualEmployeeTimeOut']</value>
      <webElementGuid>693c7b57-c298-446a-a999-c74c322624cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AddDivId']/div[2]/div/div[2]/div[2]/button</value>
      <webElementGuid>bb47c043-ffcb-49f1-83c5-3f34791143d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check In'])[1]/following::button[1]</value>
      <webElementGuid>dcdf2697-c855-4e74-8ad2-c882dcab70d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::button[3]</value>
      <webElementGuid>bc897389-6bac-425e-bc24-e6d0305c3161</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='iHealthCure'])[1]/preceding::button[1]</value>
      <webElementGuid>dc6cc310-9587-4aac-9a3d-02844ed69a2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Check Out']/parent::*</value>
      <webElementGuid>42d8dad3-d366-4327-bc57-be74f08faad0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/button</value>
      <webElementGuid>6a6a5929-8cbb-49b1-a3b3-44f3ad4913ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'IsManualEmployeeTimeOut' and (text() = 'Check Out' or . = 'Check Out')]</value>
      <webElementGuid>602e90c0-5907-4bca-855c-a70d902f454c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
