<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span</name>
   <tag></tag>
   <elementGuidId>c09cf310-fc62-4a33-92bb-1b7fda5ed040</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='CheckedInDiv_Wrapper']/div[2]/div[2]/label[4]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>00206ade-61a9-432e-a464-c195081e24d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CheckedInDiv_Wrapper&quot;)/div[@class=&quot;form-group row&quot;]/div[@class=&quot;col-md-9&quot;]/label[@class=&quot;kt-radio kt-radio--brand&quot;]/span[1]</value>
      <webElementGuid>59168695-2e18-4473-919e-f6ab5e46b0e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CheckedInDiv_Wrapper']/div[2]/div[2]/label[4]/span</value>
      <webElementGuid>9c8168c1-6eb3-4720-bd35-4fb31197288d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label[4]/span</value>
      <webElementGuid>0b2b15d9-e903-4725-895f-10f36a899f64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
