<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_60 years_1</name>
   <tag></tag>
   <elementGuidId>6837ef8e-fa0c-4452-8368-d8f8f54afa84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#15</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='15']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>96821613-0e93-4957-a2ad-907ce439601a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>78fd3be8-6345-4b8c-be9f-d94797d70893</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b1ddc419-7754-4a2b-af04-20f389487037</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>8a4bd824-2143-4fdc-9a10-11eac040db0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>f</value>
      <webElementGuid>6d69a211-d0d9-4cb0-b96c-d3c07672e207</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio-style</value>
      <webElementGuid>5faee225-4709-4f78-a1d4-7bff63bb0e2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;15&quot;)</value>
      <webElementGuid>60b6ad65-a449-43b3-92c2-88aa0b32f873</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='15']</value>
      <webElementGuid>20d22bab-832d-48b3-8f64-3ec710e1759d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ApplicationDetailTable']/tbody/tr[5]/th[2]/div/input</value>
      <webElementGuid>fa181409-a5ca-4477-86c8-44c58a8ac696</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/th[2]/div/input</value>
      <webElementGuid>7038e210-34ce-4efb-ac75-f7aa62343fec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '15' and @name = '1' and @type = 'radio']</value>
      <webElementGuid>4ca6644f-51d0-4fe9-9b09-a09f9318fe6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
