<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rented House_13</name>
   <tag></tag>
   <elementGuidId>64eb0b01-1f02-4c6e-80df-b84c4b53bf8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#59</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='59']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6919810b-382f-4931-b7f1-f6378c6b8e6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>59</value>
      <webElementGuid>10241b85-0bab-4efe-ab3a-c831dcd8058d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>ab9f0507-4c4b-42de-b507-e72e544bd3c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>8f3a536c-e27f-457f-bc5d-db5b5d0bd3c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>f</value>
      <webElementGuid>c1b57956-01c3-4d6a-ad11-a953de8d6ad6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio-style</value>
      <webElementGuid>66a9b6cd-257c-4504-83e2-a85acc1486e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;59&quot;)</value>
      <webElementGuid>5a7f561c-0f75-42aa-ade4-75ede5c93eb4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='59']</value>
      <webElementGuid>7ab9e21b-eca6-4946-9f1b-15c8946d633d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ApplicationDetailTable']/tbody/tr[49]/th[2]/div/input</value>
      <webElementGuid>fbbffc9d-55e4-4495-9e3d-5513a3966b37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[49]/th[2]/div/input</value>
      <webElementGuid>b9ed316e-4948-4481-9612-1390173c8805</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '59' and @name = '13' and @type = 'radio']</value>
      <webElementGuid>fff27699-5e4e-469e-aee4-7f454e53d93f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
