<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Motercycle  Rickshaw_11</name>
   <tag></tag>
   <elementGuidId>24f62932-1e40-47fc-8f92-5fd0cbf0cef1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#53</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='53']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>07c059f5-8b0d-4126-9909-7682478eabf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>53</value>
      <webElementGuid>1798688a-2ef1-40b8-80b5-2bb243f278c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>edf148ee-bfdd-45cb-9589-d34ee6ba460b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>9562610c-bde1-4618-9161-934bb73af7cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>f</value>
      <webElementGuid>1318fb20-8bd1-4124-b46d-9552ac72cbea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio-style</value>
      <webElementGuid>8980fdab-72e9-44bf-b96c-13ab1feb0cce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;53&quot;)</value>
      <webElementGuid>5466e926-2c37-40d4-8c1b-ca5ecd635c5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='53']</value>
      <webElementGuid>372ffbab-93b3-4c91-ba58-2eef528e2d35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ApplicationDetailTable']/tbody/tr[43]/th[2]/div/input</value>
      <webElementGuid>98e2375b-663b-457f-8131-83e2428faf21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[43]/th[2]/div/input</value>
      <webElementGuid>2ec9590a-55f8-4399-af70-05f32306bfd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '53' and @name = '11' and @type = 'radio']</value>
      <webElementGuid>caca2ad8-e825-44ed-8434-ce86c079ad77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
