<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Token No . Date .Manager_Action Delete bt_1ea955</name>
   <tag></tag>
   <elementGuidId>e9addc73-c123-4638-a230-910bd4efa6d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.Action.Delete.btn.btn-sm.btn-clean.btn-icon.btn-icon-md</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='GovtOfPunjabChequeConfigurationTypeTable']/tbody/tr/td[33]/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>26969e38-e6f9-4661-91ea-e1fe55db6bd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>57de1740-f2a3-4252-8457-a20570a965d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Action Delete btn btn-sm btn-clean btn-icon btn-icon-md</value>
      <webElementGuid>8803fd98-52d2-4245-afdf-560e2152c91a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GovtOfPunjabChequeConfigurationTypeTable&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;text-center&quot;]/a[@class=&quot;Action Delete btn btn-sm btn-clean btn-icon btn-icon-md&quot;]</value>
      <webElementGuid>0d92af55-e864-4c96-9f77-ee7154773e2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='GovtOfPunjabChequeConfigurationTypeTable']/tbody/tr/td[33]/a[2]</value>
      <webElementGuid>c72bc518-6dc5-41a0-b331-18ef61828864</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bank Name'])[2]/preceding::a[1]</value>
      <webElementGuid>b9d36c79-33f2-47c1-bab2-0326ea73b967</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bank Code'])[2]/preceding::a[1]</value>
      <webElementGuid>04eaf1fc-a318-43d4-954c-b1ba3e57f36b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[33]/a[2]</value>
      <webElementGuid>d27e7a16-12d4-472c-a03e-027b1a914f08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Delete']</value>
      <webElementGuid>90b43f52-0ab6-4182-a343-449342f872c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
