<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Token No . Date .Manager_Action Update bt_969f07</name>
   <tag></tag>
   <elementGuidId>c0983512-aa3f-4028-b894-4bdf4b9f8d86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.Action.Update.btn.btn-sm.btn-clean.btn-icon.btn-icon-md</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='GovtOfPunjabChequeConfigurationTypeTable']/tbody/tr/td[33]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>63c4c3d0-8cf9-485f-b902-5ffc5ef99d05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Update</value>
      <webElementGuid>40a3a597-7131-40cf-844a-07569403a32f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Action Update btn btn-sm btn-clean btn-icon btn-icon-md</value>
      <webElementGuid>116427d3-a2d8-4c7c-919b-7cfb8d20ed9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GovtOfPunjabChequeConfigurationTypeTable&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;text-center&quot;]/a[@class=&quot;Action Update btn btn-sm btn-clean btn-icon btn-icon-md&quot;]</value>
      <webElementGuid>f1c2d784-0062-4614-820e-cec9bbdafb29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='GovtOfPunjabChequeConfigurationTypeTable']/tbody/tr/td[33]/a</value>
      <webElementGuid>233c1944-9fba-4728-8e84-01b922a56e62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bank Name'])[2]/preceding::a[2]</value>
      <webElementGuid>12e2dce9-87f8-46ac-8d0e-e2cd1b42d169</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bank Code'])[2]/preceding::a[2]</value>
      <webElementGuid>28a5dcbb-2a3e-431e-89c6-a29b195981c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[33]/a</value>
      <webElementGuid>92e8cf37-49a3-4f81-98f2-452eaa38912c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Update']</value>
      <webElementGuid>f536aadb-ffc1-4630-9b11-15a7f3dbe3ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
