<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__AccountHeadBPaddingTop</name>
   <tag></tag>
   <elementGuidId>b4bdcaf0-da1b-4b08-a245-18f0eff7e2a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AccountHeadBPaddingTop</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AccountHeadBPaddingTop']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3992c5c9-ed1d-4ea6-8d37-0a66652a45f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>9a44072c-a634-4119-81b8-d739931e1468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>any</value>
      <webElementGuid>40a08cfd-8667-4409-bcd9-3fed0eb2f61b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AccountHeadBPaddingTop</value>
      <webElementGuid>42fd47fd-faf9-47ab-b6a8-c981d6ef1d22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AccountHeadBPaddingTop</value>
      <webElementGuid>d6383837-e75b-4881-9d59-8cde42b90690</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>Utilities.TakeOnlyNormalValidInput(this)</value>
      <webElementGuid>18840123-5069-4473-bfd1-1fee2c426b63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>b86b4ce7-10fa-4bfc-84df-f652b9bd6ca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>39a1333e-e033-4349-a7f0-2ae35a0a80ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Account Head B Padding Top </value>
      <webElementGuid>d097b81f-318b-42e4-afcb-28b9abb88c65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bv-field</name>
      <type>Main</type>
      <value>AccountHeadBPaddingTop</value>
      <webElementGuid>ca13543e-348e-4c8c-b5d7-0a4782084a30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccountHeadBPaddingTop&quot;)</value>
      <webElementGuid>e7d84022-2ca4-4286-80ad-eb26874df8b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AccountHeadBPaddingTop']</value>
      <webElementGuid>22e38df1-2711-4720-ab04-68717246f64a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myDIV']/div/div[11]/div[2]/div/div[2]/input</value>
      <webElementGuid>990879b7-9bbd-453e-9ac2-72b918b3d721</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div[2]/div/div[2]/input</value>
      <webElementGuid>a0b35a05-356a-4e83-a5bc-411f585973b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'AccountHeadBPaddingTop' and @name = 'AccountHeadBPaddingTop' and @placeholder = 'Account Head B Padding Top ']</value>
      <webElementGuid>476aed84-a5cc-410b-b9f6-186c4ad122ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
