<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Top Left Stamp A Name_TopLeftStampAName</name>
   <tag></tag>
   <elementGuidId>3add9feb-b1a4-4522-bd4d-97663fba1e8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TopLeftStampAName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='TopLeftStampAName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>842c595e-eb04-488c-a8f9-838556cb6e79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TopLeftStampAName</value>
      <webElementGuid>e1c02b5b-f179-445c-8478-b1b02b3b1550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TopLeftStampAName</value>
      <webElementGuid>86efc24d-7c9f-45e5-ae8e-0bceef99d820</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b3d11950-8921-48d2-9257-b5fbea161a12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control capitalize</value>
      <webElementGuid>7f385a37-402c-450a-a652-7c881cbc4789</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Top Left Stamp A Name </value>
      <webElementGuid>1d1b20de-d58a-4274-85c8-b10f91d56a3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TopLeftStampAName&quot;)</value>
      <webElementGuid>14d3e3a3-74e4-46a0-909d-5a4d7e51570b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='TopLeftStampAName']</value>
      <webElementGuid>ea83bff6-36eb-43f2-b00a-5f1c8c9bb5bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myDIV']/div/div[15]/div/div/div[2]/textarea</value>
      <webElementGuid>7c5c03fe-c2ca-47d1-8c2f-6ac282e00d26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>3cf1a3da-623b-411c-80f2-c52295d7c29b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'TopLeftStampAName' and @name = 'TopLeftStampAName' and @type = 'text' and @placeholder = 'Top Left Stamp A Name ']</value>
      <webElementGuid>34cda897-348e-49d3-a90c-6cf12739d1e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
