<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Open_glyphicon glyphicon-edit</name>
   <tag></tag>
   <elementGuidId>d9a0eb6a-f4e2-4467-bfab-e52443665753</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.glyphicon.glyphicon-edit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='BudgetReleaseSetupMainDataTable']/tbody/tr/td[8]/a[4]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>9c559711-ea69-48f2-9d58-e78f274b7973</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>glyphicon glyphicon-edit</value>
      <webElementGuid>83544642-95b0-4ec7-b08f-192e6bff0cd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BudgetReleaseSetupMainDataTable&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;text-center&quot;]/a[@class=&quot;Action Update btn btn-sm btn-clean btn-icon btn-icon-md&quot;]/i[@class=&quot;glyphicon glyphicon-edit&quot;]</value>
      <webElementGuid>145fd337-6e8a-46f8-9043-36070d8f34d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='BudgetReleaseSetupMainDataTable']/tbody/tr/td[8]/a[4]/i</value>
      <webElementGuid>169d4059-3185-47cb-8306-fe71f499e051</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]/i</value>
      <webElementGuid>00f48bf3-c1e9-4f4f-add3-fafa4961cf77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
