<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__ReleasedReferenceLetterNumber</name>
   <tag></tag>
   <elementGuidId>0c16caba-b910-43f0-9b22-82848b933b0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ReleasedReferenceLetterNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ReleasedReferenceLetterNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c6fec7e4-ebf9-4b92-bf3e-f0ecdefe9407</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ReleasedReferenceLetterNumber</value>
      <webElementGuid>a88aa411-d8bb-412a-82f6-7ff867678b83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ReleasedReferenceLetterNumber</value>
      <webElementGuid>b9d673f4-e69e-49a8-912e-f81fcdcf3dfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>Utilities.TakeOnlyInputNumbers(event)</value>
      <webElementGuid>65a601ea-1e6a-42bf-95bf-5be022884a1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>f17d11e9-14fe-4afc-8c21-841ec21c4535</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5f34196d-e3ba-4bfe-9c6d-61e746f05672</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4f967ddc-a9f5-482e-a381-6b634b36e07d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Released Reference Letter No.</value>
      <webElementGuid>133f93de-0d9f-4fb0-9f6c-d5ddf6645cd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ReleasedReferenceLetterNumber&quot;)</value>
      <webElementGuid>bfb25caf-3dcb-49f3-be2f-7d25addc9c8c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ReleasedReferenceLetterNumber']</value>
      <webElementGuid>b91c8e57-17d2-4310-a46c-1faedc2eb639</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myDIV']/div[2]/div[2]/input</value>
      <webElementGuid>0a921794-78ff-4cec-bac3-e5c4c219327c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>fc7c0d22-ae6e-4778-ba9f-7bd712f1c28f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ReleasedReferenceLetterNumber' and @name = 'ReleasedReferenceLetterNumber' and @type = 'text' and @placeholder = 'Released Reference Letter No.']</value>
      <webElementGuid>3b93709e-bc19-4b81-81cf-9b5d127a7a7d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
