<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Close_UpdateSubmit</name>
   <tag></tag>
   <elementGuidId>db54669d-0e80-4776-9d39-c40f9ab493e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UpdateSubmit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UpdateSubmit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3b4d85a4-d98d-4132-8a2c-c77c684c401e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3899b846-6fae-4ef9-a1f6-9be58206835f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary pull-right</value>
      <webElementGuid>cb78e0e0-69fd-4e17-8986-5c1ad730c43c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UpdateSubmit</value>
      <webElementGuid>9a06750c-0be5-4120-a157-82ccc7d07124</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>d56b7004-f6be-49c4-9143-3d406cf31355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UpdateSubmit&quot;)</value>
      <webElementGuid>8a52fc5e-d78d-448a-9384-39ca1175fb6a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UpdateSubmit']</value>
      <webElementGuid>3a95f3fa-5a47-4bc8-a53a-89823553c4cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='myDIV']/div[8]/input)[2]</value>
      <webElementGuid>ec73d452-fe15-4fdd-9f71-6cac05937ebe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[8]/input</value>
      <webElementGuid>fa72c84d-e924-484d-8960-591d559f9b35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'UpdateSubmit']</value>
      <webElementGuid>3567c8c4-f2b7-40bf-a34a-dc9b8bf28042</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
