<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select Reference Letter No.234</name>
   <tag></tag>
   <elementGuidId>1e6d0792-0704-44d1-a5a1-9f0ce8c74625</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ReferenceLetterId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ReferenceLetterId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b9991ece-7076-4f24-90cf-b71f459321e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectpicker form-control</value>
      <webElementGuid>37cb9768-794c-4894-86d2-27bef1f0493e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-live-search</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e0f9315d-d6a9-4ded-885c-7d13ec2c1f6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ReferenceLetterId</value>
      <webElementGuid>3deef407-c712-47ce-a668-e3dad752fd44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ReferenceLetterId</value>
      <webElementGuid>95dde704-4498-4742-b3ff-9515287a269a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-98</value>
      <webElementGuid>71888d1e-9336-4f73-9b69-f4e615aab700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Reference Letter No.
234
</value>
      <webElementGuid>0eeb3f17-ffde-49cf-b2c5-313980d1294a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ReferenceLetterId&quot;)</value>
      <webElementGuid>6f6a6627-1e62-4293-acb0-0c917197ce46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ReferenceLetterId']</value>
      <webElementGuid>b3c38758-8f42-4aeb-8b72-b48082ff3a49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myDIV']/div/div[2]/div/select</value>
      <webElementGuid>3557dd57-3744-44a5-8011-dd34ebd4379a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::select[1]</value>
      <webElementGuid>68c67fe7-e93e-4b9f-a4de-8b763c408caf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Reference Letter No.'])[2]/preceding::select[1]</value>
      <webElementGuid>7974db8a-4210-495e-97be-02223b3ebdcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Reference Letter No.'])[3]/preceding::select[1]</value>
      <webElementGuid>b2e236c1-332f-4fcd-9ee6-cae5c6f99f2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>b0eeb1f6-0dc5-4582-aac0-a829ee902288</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'ReferenceLetterId' and @name = 'ReferenceLetterId' and (text() = 'Select Reference Letter No.
234
' or . = 'Select Reference Letter No.
234
')]</value>
      <webElementGuid>cbe4b677-0387-4ea1-a144-ae237e4cff75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
