<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__ChallanNo</name>
   <tag></tag>
   <elementGuidId>d8a43f58-17b4-4deb-820b-1e7ce0165708</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ChallanNo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ChallanNo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d2ca5bdd-97c9-4744-a352-457a1e2430c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ChallanNo</value>
      <webElementGuid>6117edb5-7a22-4818-9810-cbff3048b1e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ChallanNo</value>
      <webElementGuid>03d59040-4006-4e78-845c-78ce5aefee04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d54f769d-773c-4dc6-b68e-f9d64791eb34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control capitalize</value>
      <webElementGuid>7d27dca9-bb1e-4e6b-b869-42953db40923</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Challan No</value>
      <webElementGuid>9c141741-649f-4b52-97c6-1add5dbced79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bv-field</name>
      <type>Main</type>
      <value>ChallanNo</value>
      <webElementGuid>4a4fbc8d-a3db-452d-919a-d98b03576503</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ChallanNo&quot;)</value>
      <webElementGuid>5faf5941-c624-4814-b327-2d92c25ff26b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ChallanNo']</value>
      <webElementGuid>866dc919-1d67-4686-9089-9a5221ef32ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FormRefundMedicine']/div/div[2]/div/div/div[2]/div/div[2]/input</value>
      <webElementGuid>6ec44886-5fa0-4c8d-b2de-4494aff83531</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>e2528450-17e0-4838-8f25-3cdfb36b02c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ChallanNo' and @name = 'ChallanNo' and @type = 'text' and @placeholder = 'Enter Challan No']</value>
      <webElementGuid>96b9118a-5639-4948-9786-a91632e2ec98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
