<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ul_Pakistan Military Accounts Department (C_d36326</name>
   <tag></tag>
   <elementGuidId>2fd10a93-19de-46ed-979b-a1127356ed6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='select2-PanelOrganizationId-results']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-PanelOrganizationId-results</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
      <webElementGuid>64c1384f-95df-49b7-9187-4102a0b6c68e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__options</value>
      <webElementGuid>af529076-f7a6-4843-912d-37b19d13d2e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>4a619778-4fc7-4550-8d14-752ae34cb479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-PanelOrganizationId-results</value>
      <webElementGuid>9528db73-6a82-4186-8d0a-2dd1fe7fbb62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>147a116a-5dc8-4a68-a3aa-b1878f5c2caf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e1d8e63b-ac27-489f-b681-bb21203d6c78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pakistan Military Accounts Department (CMA)Pakistan NavyPakistan International AirlinesPakistan ArmyPakistan Bait-Ul-MalPakistan Bait-Ul-Mal-Regional Office-ICTPakistan ArmedPakistan Airforce</value>
      <webElementGuid>96cb8b3d-a38a-42b9-a946-1ba794bf4691</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-PanelOrganizationId-results&quot;)</value>
      <webElementGuid>ae1ca47a-7513-4df7-987f-9e6db9ecd6b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//ul[@id='select2-PanelOrganizationId-results']</value>
      <webElementGuid>4813d84e-bcde-41e6-90da-e46df2b34739</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'select2-PanelOrganizationId-results', '&quot;', ')')])[1]/following::ul[1]</value>
      <webElementGuid>bb633cc1-b2c9-4267-adf5-549c3a9c1e4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Set Waiting Time'])[1]/following::ul[1]</value>
      <webElementGuid>3632063d-0e8a-412d-8a5d-3a9f902654e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/ul</value>
      <webElementGuid>5aa1f138-a8bf-49b1-a4a8-51af435292f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ul[@id = 'select2-PanelOrganizationId-results' and (text() = 'Pakistan Military Accounts Department (CMA)Pakistan NavyPakistan International AirlinesPakistan ArmyPakistan Bait-Ul-MalPakistan Bait-Ul-Mal-Regional Office-ICTPakistan ArmedPakistan Airforce' or . = 'Pakistan Military Accounts Department (CMA)Pakistan NavyPakistan International AirlinesPakistan ArmyPakistan Bait-Ul-MalPakistan Bait-Ul-Mal-Regional Office-ICTPakistan ArmedPakistan Airforce')]</value>
      <webElementGuid>d82ca65e-f8ef-4ef2-9f68-6e6152b6ec64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
