<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_PDF</name>
   <tag></tag>
   <elementGuidId>acafd15e-1c3b-4a95-b872-466581fb546d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='PatientAccountDetail']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.kt-nav__link-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2a942ceb-0f09-4ee4-a7a7-74a413a33b1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>kt-nav__link-text</value>
      <webElementGuid>072a8d5c-d21e-4261-9ac6-ad9549fa31c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PDF</value>
      <webElementGuid>662581d4-a9e2-4fb1-9d3f-98bd92f55360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PatientAccountDetail&quot;)/span[@class=&quot;kt-nav__link-text&quot;]</value>
      <webElementGuid>95bd5715-6290-4de0-bd09-8d00d5434d56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='PatientAccountDetail']/span</value>
      <webElementGuid>5fe0d4f9-2854-4a36-be3f-9fbf1e39d274</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose an option'])[1]/following::span[1]</value>
      <webElementGuid>ae331fa9-b1cb-4151-8a19-f67c97b6ebc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date Range'])[1]/preceding::span[1]</value>
      <webElementGuid>06a59c50-26e1-42ad-8148-151f1f7ff219</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asset'])[1]/preceding::span[2]</value>
      <webElementGuid>78454ffa-8e35-4609-acf7-fc22521f2db4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PDF']/parent::*</value>
      <webElementGuid>8e0769c5-61a2-4c89-acd8-127785260392</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/ul/li[2]/a/span</value>
      <webElementGuid>1115e2d1-2b6a-453e-9c62-b011abe514ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'PDF' or . = 'PDF')]</value>
      <webElementGuid>c947ddcd-0394-498e-a379-5ee4ce567961</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
