<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Request Remarks_SubmitRequestReceptio_b959fa</name>
   <tag></tag>
   <elementGuidId>acf8aa4f-1f9d-4757-81a9-6ae6b3b32a21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='SubmitRequestReceptionCashRequisition']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#SubmitRequestReceptionCashRequisition</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>45fb8483-c846-4c05-b01d-b14085e94c31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d299b21e-12cc-445d-ad6c-e2fa016453f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SubmitRequestReceptionCashRequisition</value>
      <webElementGuid>d5cb9b61-963f-460c-a31c-9f015f23ca25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>SaveForm()</value>
      <webElementGuid>303497f5-234f-4d50-9ca2-5f2bade09776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>efd26024-2a07-4674-b64c-a95da1408e30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>871b7a51-25fa-4f7b-b969-139ecff96278</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SubmitRequestReceptionCashRequisition&quot;)</value>
      <webElementGuid>a8c3d819-10de-40b4-bfe3-172ccbd0de09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='SubmitRequestReceptionCashRequisition']</value>
      <webElementGuid>00812cfc-7e54-4da0-8f91-7945a953adf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hideform']/input</value>
      <webElementGuid>c48dcac9-ee4c-44ee-86cf-2d431a8d717c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/div/input</value>
      <webElementGuid>b298457f-5cac-4a80-8d11-58c658f42c6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'SubmitRequestReceptionCashRequisition']</value>
      <webElementGuid>bacde4ed-65e2-4ba1-a956-43e93d4691a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
