<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Request Remarks_RequestedRemarks</name>
   <tag></tag>
   <elementGuidId>79b019b6-3c1c-4c38-bb6f-9d0a55477c6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='RequestedRemarks']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#RequestedRemarks</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>2753f64f-873a-4180-b1de-b416c2070e49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1daae06f-383a-4843-bfd8-48115ce42400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>0cc88a5f-0900-4c52-b411-72d2c6026e2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>RequestedRemarks</value>
      <webElementGuid>a2bbd905-ceea-490f-9e3a-0d08cecbc3a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>RequestedRemarks</value>
      <webElementGuid>6c0e129b-d19a-4e7b-9075-9a2d43241390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Request Remarks</value>
      <webElementGuid>40c22bfb-9b8b-472b-a6f2-0578c10e8cc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e81274fc-e25a-4cbe-a39e-4b5ded6f8724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RequestedRemarks&quot;)</value>
      <webElementGuid>3d2fd029-97e2-4cc1-a219-144a0603980a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='RequestedRemarks']</value>
      <webElementGuid>8bc22461-fd12-4cf4-b1b8-bcca090e1876</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='ReceptionCashRequisitionForm']/div/div/div[3]/div[2]/textarea</value>
      <webElementGuid>d899eacb-d500-43cc-bafa-f1c982b8f4b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>6408d53b-3621-4da6-a38e-a8020475ab23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@type = 'text' and @id = 'RequestedRemarks' and @name = 'RequestedRemarks' and @placeholder = 'Enter Request Remarks']</value>
      <webElementGuid>6a879662-8c68-44f7-a408-61116e7a7846</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
